import type { Level } from "@/lib/types";

// Luganda Beginner — Unit 0 only (ear first).
// Content rule: a lesson may only use words/contrasts already taught.
// Speak-phrase is off for lg. Verify length pairs with a speaker before
// treating this as production.

export const beginner: Level = {
  id: "beginner",
  title: "Beginner",
  blurb: "Hear length first. Greetings come in Unit 1.",
  units: [
    {
      id: "lg-u0-sounds",
      title: "The ear first",
      subtitle: "Short vs long. Ny. Ng'. Doubling.",
      lessons: [
        {
          id: "lg-u0-vowels",
          title: "The five vowels",
          subtitle: "a e i o u — one beat each",
          icon: "Aa",
          skill: "listening",
          xp: 20,
          teach: [
            {
              char: "a",
              romaji: "a",
              mnemonic: "One beat. Open, like the 'a' in 'father'. Never the English 'ay' in 'name'.",
              mnemonicEmoji: "\u{1F9B7}",
              example: { word: "a", romaji: "a", meaning: "short a" },
            },
            {
              char: "e",
              romaji: "e",
              mnemonic: "One beat. Like 'e' in 'bed', but held clean — not a slide into 'ee'.",
              mnemonicEmoji: "\u{1F95A}",
              example: { word: "e", romaji: "e", meaning: "short e" },
            },
            {
              char: "i",
              romaji: "i",
              mnemonic: "One beat. Like 'ee' in 'see', cut short. Not English 'i' in 'sit'.",
              mnemonicEmoji: "\u{1FAA1}",
              example: { word: "i", romaji: "i", meaning: "short i" },
            },
            {
              char: "o",
              romaji: "o",
              mnemonic: "One beat. Pure 'o', like 'or' without the English 'r'. Not 'oh-oo'.",
              mnemonicEmoji: "\u{1F7E0}",
              example: { word: "o", romaji: "o", meaning: "short o" },
            },
            {
              char: "u",
              romaji: "u",
              mnemonic: "One beat. Like 'oo' in 'food', cut short. Not 'yu' in 'use'.",
              mnemonicEmoji: "\u{1F319}",
              example: { word: "u", romaji: "u", meaning: "short u" },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "How many vowel letters does Luganda write?",
              display: "a e i o u",
              options: ["5", "7", "10"],
              answer: "5",
              note: "Five letters. Each also has a long form, taught next. That is not five extra letters — it is two beats.",
            },
            {
              type: "translate-choice",
              prompt: "The letter i is closest to which English sound?",
              display: "i",
              options: ["sit", "see (but shorter)", "sigh"],
              answer: "see (but shorter)",
              note: "Cut it to one beat. Do not say English 'sit'.",
            },
            {
              type: "type-answer",
              prompt: "Type the five short vowels in order, spaces between",
              display: "the Luganda vowel row",
              answer: "a e i o u",
              accept: ["aeiou", "a e i o u"],
            },
            {
              type: "match-pairs",
              prompt: "Match the letter to the closest English hook",
              pairs: [
                { left: "a", right: "father" },
                { left: "o", right: "or (no r)" },
                { left: "u", right: "food (short)" },
              ],
            },
            {
              type: "listen-choice",
              prompt: "Listen. Which vowel is this?",
              audio: "a",
              options: ["a", "e", "o"],
              answer: "a",
            },
          ],
        },
        {
          id: "lg-u0-ny-ng",
          title: "Ny and ng'",
          subtitle: "Two letters, one sound",
          icon: "\u0272",
          skill: "listening",
          xp: 20,
          teach: [
            {
              kind: "phrase",
              term: "ny",
              reading: "ny",
              meaning: "One consonant. Like Spanish \u00f1, or the 'ni' in 'onion'. Never 'n' + 'y' as two taps.",
              note: "Written ny. Count it as one sound when you clap syllables.",
              uses: [
                {
                  situation: "In a word you already meet in food later",
                  english: "meat",
                  example: "nyama",
                },
              ],
              check: {
                prompt: "How many sounds is ny?",
                options: ["one", "two (n + y)"],
                answer: "one",
                note: "One consonant. If you say 'n-yama' you have added a beat.",
              },
            },
            {
              kind: "phrase",
              term: "ng'",
              reading: "ng'",
              meaning: "The sound in 'singer', not the sound in 'finger'. Written ng' when it is this sound at the start of a syllable.",
              note: "The apostrophe marks 'singer-ng', not 'finger-ngg'.",
              uses: [
                {
                  situation: "A word you will need at a market",
                  english: "cow",
                  example: "ng'ombe",
                },
              ],
              check: {
                prompt: "ng'ombe starts like which English word?",
                options: ["finger", "singer"],
                answer: "singer",
                note: "No hard 'g' after the ng. Soft, one sound.",
              },
            },
            {
              kind: "phrase",
              term: "nyama",
              reading: "nyama",
              meaning: "meat",
              context: "You are only learning the shape of ny here. Food unit comes later.",
              parts: [
                { kana: "ny", reading: "ny", note: "one consonant" },
                { kana: "a", reading: "a" },
                { kana: "m", reading: "m" },
                { kana: "a", reading: "a" },
              ],
            },
            {
              kind: "phrase",
              term: "ng'ombe",
              reading: "ng'ombe",
              meaning: "cow",
              parts: [
                { kana: "ng'", reading: "ng'", note: "singer-ng, one consonant" },
                { kana: "o", reading: "o" },
                { kana: "mb", reading: "mb", note: "mb is a nasal compound — later. Hear it as one lump." },
                { kana: "e", reading: "e" },
              ],
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "ny is",
              display: "ny",
              options: ["n then y", "one sound", "silent"],
              answer: "one sound",
            },
            {
              type: "translate-choice",
              prompt: "What does nyama mean?",
              display: "nyama",
              options: ["cow", "meat", "water"],
              answer: "meat",
            },
            {
              type: "translate-choice",
              prompt: "What does ng'ombe mean?",
              display: "ng'ombe",
              options: ["meat", "cow", "child"],
              answer: "cow",
            },
            {
              type: "listen-choice",
              prompt: "Listen. Which word?",
              audio: "nyama",
              options: ["nyama", "ng'ombe", "kola"],
              answer: "nyama",
              note: "kola is not taught yet — ignore it if TTS is messy; the contrast is ny vs ng'.",
            },
            {
              type: "match-pairs",
              prompt: "Match the cluster to the hook",
              pairs: [
                { left: "ny", right: "onion / \u00f1" },
                { left: "ng'", right: "singer" },
                { left: "nyama", right: "meat" },
              ],
            },
            {
              type: "type-answer",
              prompt: "Type the Luganda for 'meat'",
              display: "meat",
              answer: "nyama",
              accept: ["Nyama"],
            },
          ],
        },
        {
          id: "lg-u0-length",
          title: "Two beats",
          subtitle: "Long vowel or double consonant — both change the word",
          icon: "\u23F3",
          skill: "listening",
          xp: 25,
          teach: [
            {
              kind: "phrase",
              term: "kola",
              reading: "kola",
              meaning: "work / do",
              note: "Short o. One beat on ko.",
              contrast: {
                label: "Same letters, extra beat, different verb",
                a: { word: "kola", romaji: "kola", meaning: "work / do" },
                b: { word: "koola", romaji: "koola", meaning: "weed (the garden)" },
              },
              check: {
                prompt: "koola with a long oo means",
                options: ["work", "weed"],
                answer: "weed",
                note: "Double the vowel in writing = two beats in the mouth.",
              },
            },
            {
              kind: "phrase",
              term: "tuma",
              reading: "tuma",
              meaning: "send",
              contrast: {
                label: "Hear the u",
                a: { word: "tuma", romaji: "tuma", meaning: "send" },
                b: { word: "tuuma", romaji: "tuuma", meaning: "give a name" },
              },
            },
            {
              kind: "phrase",
              term: "bana",
              reading: "bana",
              meaning: "four",
              contrast: {
                label: "The pair you will actually mix up with family talk later",
                a: { word: "bana", romaji: "bana", meaning: "four" },
                b: { word: "baana", romaji: "baana", meaning: "children" },
              },
              check: {
                prompt: "baana with long aa means",
                options: ["four", "children"],
                answer: "children",
              },
            },
            {
              kind: "phrase",
              term: "kuba",
              reading: "kuba",
              meaning: "to be",
              note: "Doubling the consonant is the same family of mistake as doubling the vowel. Speakers call both 'stressing'.",
              contrast: {
                label: "Single b vs double bb",
                a: { word: "kuba", romaji: "kuba", meaning: "to be" },
                b: { word: "kubba", romaji: "kubba", meaning: "to steal" },
              },
              check: {
                prompt: "kubba (double b) means",
                options: ["to be", "to steal"],
                answer: "to steal",
                note: "Hold the b. Do not turn it into a long u.",
              },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "kola means",
              display: "kola",
              options: ["work / do", "weed", "steal"],
              answer: "work / do",
            },
            {
              type: "translate-choice",
              prompt: "koola means",
              display: "koola",
              options: ["work / do", "weed", "send"],
              answer: "weed",
              note: "Two beats on oo.",
            },
            {
              type: "translate-choice",
              prompt: "baana means",
              display: "baana",
              options: ["four", "children", "cow"],
              answer: "children",
            },
            {
              type: "listen-choice",
              prompt: "Listen. Short or long o?",
              audio: "koola",
              options: ["kola (work)", "koola (weed)"],
              answer: "koola (weed)",
            },
            {
              type: "listen-choice",
              prompt: "Listen. Which verb?",
              audio: "tuma",
              options: ["tuma (send)", "tuuma (name)"],
              answer: "tuma (send)",
            },
            {
              type: "category-sort",
              prompt: "Park each word: one beat or two",
              categories: ["short (1 beat)", "long / doubled (2 beats)"],
              items: [
                { label: "kola", romaji: "work", category: "short (1 beat)" },
                { label: "koola", romaji: "weed", category: "long / doubled (2 beats)" },
                { label: "tuma", romaji: "send", category: "short (1 beat)" },
                { label: "tuuma", romaji: "name", category: "long / doubled (2 beats)" },
                { label: "bana", romaji: "four", category: "short (1 beat)" },
                { label: "baana", romaji: "children", category: "long / doubled (2 beats)" },
                { label: "kuba", romaji: "to be", category: "short (1 beat)" },
                { label: "kubba", romaji: "to steal", category: "long / doubled (2 beats)" },
              ],
              note: "Long vowel and double consonant both cost a second beat.",
            },
            {
              type: "type-answer",
              prompt: "Type the Luganda for 'children'",
              display: "children",
              answer: "baana",
              accept: ["Baana"],
              note: "Double a. bana is 'four'.",
            },
            {
              type: "match-pairs",
              prompt: "Match the written form to the meaning",
              pairs: [
                { left: "kola", right: "work / do" },
                { left: "kubba", right: "to steal" },
                { left: "tuuma", right: "give a name" },
              ],
            },
          ],
        },
        {
          id: "lg-u0-checkpoint",
          title: "Dojo checkpoint",
          subtitle: "Prove the ear before greetings",
          icon: "\u26E9\uFE0F",
          skill: "listening",
          xp: 30,
          checkpoint: true,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Listen. Which word?",
              audio: "baana",
              options: ["bana", "baana", "nyama"],
              answer: "baana",
              note: "Two-beat aa. Children, not four.",
            },
            {
              type: "listen-choice",
              prompt: "Listen. Which verb?",
              audio: "kola",
              options: ["kola", "koola", "kuba"],
              answer: "kola",
            },
            {
              type: "category-sort",
              prompt: "Park each item",
              categories: ["vowel letter", "one-sound cluster", "two-beat word"],
              items: [
                { label: "i", category: "vowel letter" },
                { label: "u", category: "vowel letter" },
                { label: "ny", category: "one-sound cluster" },
                { label: "ng'", category: "one-sound cluster" },
                { label: "koola", category: "two-beat word" },
                { label: "baana", category: "two-beat word" },
              ],
            },
            {
              type: "match-pairs",
              prompt: "Match",
              pairs: [
                { left: "nyama", right: "meat" },
                { left: "ng'ombe", right: "cow" },
                { left: "kuba", right: "to be" },
                { left: "kubba", right: "to steal" },
              ],
            },
            {
              type: "type-answer",
              prompt: "Type the short-vowel word for 'work / do'",
              display: "work / do",
              answer: "kola",
              accept: ["Kola"],
            },
            {
              type: "translate-choice",
              prompt: "A long Luganda vowel is written",
              display: "two beats",
              options: ["with an accent mark", "by doubling the letter", "in capitals"],
              answer: "by doubling the letter",
              note: "aa ee ii oo uu. Exception later: length at the edge of a word is not always written double.",
            },
          ],
        },
      ],
    },
  ],
};
