import type { Level } from "@/lib/types";

// Unit 6: Katakana Foundations (Lang-katakana-1.7-plan.md, owner-approved
// 2026-09-22). Same 46 sounds as hiragana (Unit 1) — new shapes only, so
// this moves faster: 5 lessons instead of hiragana's 10, rows bundled
// 2-3 per lesson. The real new difficulty isn't sound acquisition, it's
// shape confusion (シ/ツ, ソ/ン, ノ/メ) — see kana.ts's lookalikePairs and
// the `contrast` fields below, which deliberately land the SECOND-taught
// half of each pair (never the first, since nothing exists yet to compare
// against) referencing back to the one already met.
export const intermediate: Level = {
  id: "intermediate",
  title: "Intermediate",
  blurb: "Katakana, particles, verbs & everyday conversation.",
  units: [
    // ===== UNIT 6: Katakana Foundations =====================================
    {
      id: "u6-katakana",
      title: "Katakana Foundations",
      subtitle: "Same sounds, new shapes — read menus, signs & loanwords",
      lessons: [
        {
          id: "u6-katakana-vowels-k-s",
          title: "Katakana: Vowels, K & S",
          subtitle: "ア イ ウ エ オ　カ行　サ行",
          icon: "ア",
          skill: "reading",
          xp: 30,
          teach: [
            {
              char: "ア",
              romaji: "a",
              mnemonic: "ア is あ with the curves squared off — katakana is generally sharper and more angular than hiragana. Same 'ah' sound.",
              mnemonicEmoji: "🔺",
              example: { word: "アイス", romaji: "aisu", meaning: "ice cream" },
            },
            {
              char: "イ",
              romaji: "i",
              mnemonic: "イ is two short strokes, like い stripped down to its skeleton.",
              mnemonicEmoji: "🪑",
              example: { word: "イス", romaji: "isu", meaning: "chair" },
            },
            {
              char: "ウ",
              romaji: "u",
              mnemonic: "ウ is う's roof and hook, without the curl underneath.",
              mnemonicEmoji: "🐰",
              example: { word: "ウサギ", romaji: "usagi", meaning: "rabbit" },
            },
            {
              char: "エ",
              romaji: "e",
              mnemonic: "エ is three flat strokes stacked like a capital 'エ'-shaped ladder — nothing like curly え, memorize it fresh.",
              mnemonicEmoji: "🚉",
              example: { word: "エキ", romaji: "eki", meaning: "station" },
            },
            {
              char: "オ",
              romaji: "o",
              mnemonic: "オ keeps お's kicking-leg stroke but drops the loop — same 'oh' sound, leaner shape.",
              mnemonicEmoji: "👹",
              example: { word: "オニ", romaji: "oni", meaning: "ogre" },
            },
            {
              char: "カ",
              romaji: "ka",
              mnemonic: "カ is か with the loop shaved off — two straight strokes, same 'ka'.",
              mnemonicEmoji: "☔",
              example: { word: "カサ", romaji: "kasa", meaning: "umbrella" },
            },
            {
              char: "キ",
              romaji: "ki",
              mnemonic: "キ keeps き's cross-strokes but straightens the tail — still 'ki'.",
              mnemonicEmoji: "🦪",
              example: { word: "カキ", romaji: "kaki", meaning: "oyster" },
            },
            {
              char: "ク",
              romaji: "ku",
              mnemonic: "ク is a sharp checkmark — く's curve, straightened into an angle.",
              mnemonicEmoji: "👟",
              example: { word: "クツ", romaji: "kutsu", meaning: "shoes" },
            },
            {
              char: "ケ",
              romaji: "ke",
              mnemonic: "ケ looks like け with its loop cut — three strokes, same 'ke'.",
              mnemonicEmoji: "🐟",
              example: { word: "サケ", romaji: "sake", meaning: "salmon" },
            },
            {
              char: "コ",
              romaji: "ko",
              mnemonic: "コ is two flat strokes like a box with the right side open — the same shape idea as こ, squared off.",
              mnemonicEmoji: "🍫",
              example: { word: "ココア", romaji: "kokoa", meaning: "cocoa" },
            },
            {
              char: "サ",
              romaji: "sa",
              mnemonic: "サ keeps さ's cross-stroke but drops the curl at the bottom.",
              mnemonicEmoji: "🐵",
              example: { word: "サル", romaji: "saru", meaning: "monkey" },
            },
            {
              char: "シ",
              romaji: "shi",
              mnemonic: "シ is three short strokes, the bottom one sweeping up and to the right — like water splashing. Heads up: ツ (next lesson) looks similar but sweeps the OTHER way.",
              mnemonicEmoji: "🦌",
              example: { word: "シカ", romaji: "shika", meaning: "deer" },
            },
            {
              char: "ス",
              romaji: "su",
              mnemonic: "ス is す's hook, straightened into two clean strokes.",
              mnemonicEmoji: "🍉",
              example: { word: "スイカ", romaji: "suika", meaning: "watermelon" },
            },
            {
              char: "セ",
              romaji: "se",
              mnemonic: "セ is せ's cross-stroke and hook, angled instead of curved.",
              mnemonicEmoji: "🌍",
              example: { word: "セカイ", romaji: "sekai", meaning: "world" },
            },
            {
              char: "ソ",
              romaji: "so",
              mnemonic: "ソ is two short strokes, the top one steep and starting high. Heads up: ン (two lessons from now) looks similar but sits lower and flatter — you'll come back to this pair.",
              mnemonicEmoji: "🌌",
              example: { word: "ソラ", romaji: "sora", meaning: "sky" },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "ア",
              options: ["a", "i", "u", "e"],
              answer: "a",
              note: "ア is あ with the curves squared off.",
            },
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "カ",
              options: ["ka", "sa", "ku", "ke"],
              answer: "ka",
              note: "カ = か, shape sharpened.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "スイカ",
              answer: "suika",
              note: "ス + イ + カ — 'watermelon'.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this character",
              display: "シ",
              answer: "shi",
              note: "Bottom stroke sweeps up-and-right. Don't mix it up with ツ later.",
            },
            {
              type: "listen-choice",
              prompt: "Listen and tap the character you hear",
              audio: "ソ",
              options: ["ソ", "サ", "セ", "コ"],
              answer: "ソ",
            },
            {
              type: "match-pairs",
              prompt: "Match each katakana character to its sound",
              pairs: [
                { left: "エ", right: "e" },
                { left: "ケ", right: "ke" },
                { left: "ス", right: "su" },
                { left: "シ", right: "shi" },
              ],
            },
            {
              type: "category-sort",
              prompt: "Sort: hiragana vs katakana",
              categories: ["ひらがな", "カタカナ"],
              items: [
                { label: "あ", romaji: "a", category: "ひらがな" },
                { label: "ア", romaji: "a", category: "カタカナ" },
                { label: "か", romaji: "ka", category: "ひらがな" },
                { label: "カ", romaji: "ka", category: "カタカナ" },
              ],
              note: "Same sounds, two different sets of shapes — katakana is generally the sharper, more angular one.",
            },
            {
              type: "build-sentence",
              prompt: "Build 'watermelon' (suika)",
              display: "watermelon",
              tiles: ["ス", "イ", "カ"],
              answer: ["ス", "イ", "カ"],
            },
          ],
        },
        {
          id: "u6-katakana-t-n-h",
          title: "Katakana: T, N & H",
          subtitle: "タ行　ナ行　ハ行",
          icon: "タ",
          skill: "reading",
          xp: 30,
          teach: [
            {
              char: "タ",
              romaji: "ta",
              mnemonic: "タ keeps た's cross-stroke, straightened into two sharp lines.",
              mnemonicEmoji: "🐙",
              example: { word: "タコ", romaji: "tako", meaning: "octopus" },
            },
            {
              char: "チ",
              romaji: "chi",
              mnemonic: "チ is ち's hook, squared into two clean strokes.",
              mnemonicEmoji: "🐝",
              example: { word: "ハチ", romaji: "hachi", meaning: "bee / eight" },
            },
            {
              char: "ツ",
              romaji: "tsu",
              mnemonic: "ツ is three short strokes, the bottom one sweeping down and to the left — the mirror image of シ's upward sweep.",
              mnemonicEmoji: "🐟",
              example: { word: "ツナ", romaji: "tsuna", meaning: "tuna" },
              contrast: {
                label: "Don't mix up with シ",
                a: { word: "シ", romaji: "shi", meaning: "bottom stroke sweeps up-and-right (last lesson)" },
                b: { word: "ツ", romaji: "tsu", meaning: "bottom stroke sweeps down-and-left" },
              },
            },
            {
              char: "テ",
              romaji: "te",
              mnemonic: "テ is て's hook, straightened into a cross-stroke over a hook.",
              mnemonicEmoji: "📝",
              example: { word: "テスト", romaji: "tesuto", meaning: "test" },
            },
            {
              char: "ト",
              romaji: "to",
              mnemonic: "ト is a short vertical stroke crossed by a short diagonal — と's curve, straightened.",
              mnemonicEmoji: "🍅",
              example: { word: "トマト", romaji: "tomato", meaning: "tomato" },
            },
            {
              char: "ナ",
              romaji: "na",
              mnemonic: "ナ is な's cross-stroke and hook, angled instead of curved.",
              mnemonicEmoji: "🔪",
              example: { word: "ナイフ", romaji: "naifu", meaning: "knife" },
            },
            {
              char: "ニ",
              romaji: "ni",
              mnemonic: "ニ is two flat horizontal strokes — に with the left stem removed.",
              mnemonicEmoji: "🥩",
              example: { word: "ニク", romaji: "niku", meaning: "meat" },
            },
            {
              char: "ヌ",
              romaji: "nu",
              mnemonic: "ヌ keeps ぬ's crossing stroke but drops the end loop.",
              mnemonicEmoji: "🐕",
              example: { word: "イヌ", romaji: "inu", meaning: "dog" },
              contrast: {
                label: "Same word, different register",
                a: { word: "いぬ", romaji: "inu", meaning: "the normal way to write it (hiragana/kanji)" },
                b: { word: "イヌ", romaji: "inu", meaning: "casual/emphasis katakana — you'll see this too, but いぬ/犬 is standard" },
              },
            },
            {
              char: "ネ",
              romaji: "ne",
              mnemonic: "ネ is ね's loop, opened up into a straight hook.",
              mnemonicEmoji: "🐈",
              example: { word: "ネコ", romaji: "neko", meaning: "cat" },
            },
            {
              char: "ノ",
              romaji: "no",
              mnemonic: "ノ is a single diagonal stroke, top-right to bottom-left — the simplest character in the whole script. Heads up: メ (next lesson) is this exact stroke plus a second one crossing it.",
              mnemonicEmoji: "🍄",
              example: { word: "キノコ", romaji: "kinoko", meaning: "mushroom" },
            },
            {
              char: "ハ",
              romaji: "ha",
              mnemonic: "ハ is two strokes splayed outward — は's shape, stripped to its frame.",
              mnemonicEmoji: "🌸",
              example: { word: "ハナ", romaji: "hana", meaning: "flower" },
            },
            {
              char: "ヒ",
              romaji: "hi",
              mnemonic: "ヒ is ひ's hook, straightened into an angle.",
              mnemonicEmoji: "😌",
              example: { word: "ヒマ", romaji: "hima", meaning: "free time" },
            },
            {
              char: "フ",
              romaji: "fu",
              mnemonic: "フ is a single sweeping stroke — ふ with everything but the top curl removed.",
              mnemonicEmoji: "⛴️",
              example: { word: "フネ", romaji: "fune", meaning: "boat" },
            },
            {
              char: "ヘ",
              romaji: "he",
              mnemonic: "ヘ is identical to hiragana へ — the one character katakana didn't bother changing.",
              mnemonicEmoji: "😅",
              example: { word: "ヘタ", romaji: "heta", meaning: "unskilled, bad at" },
            },
            {
              char: "ホ",
              romaji: "ho",
              mnemonic: "ホ keeps ほ's extra top line but straightens the rest into four clean strokes.",
              mnemonicEmoji: "🏨",
              example: { word: "ホテル", romaji: "hoteru", meaning: "hotel" },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "ツ",
              options: ["tsu", "shi", "chi", "to"],
              answer: "tsu",
              note: "Bottom stroke sweeps down-and-left — the mirror of シ.",
            },
            {
              type: "translate-choice",
              prompt: "Which character is 'he'?",
              display: "❓",
              options: ["ヘ", "ハ", "ホ", "フ"],
              answer: "ヘ",
              note: "ヘ is the one katakana character identical to its hiragana twin, へ.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "ホテル",
              answer: "hoteru",
              note: "'Hotel' — you'll need this word constantly.",
            },
            {
              type: "listen-choice",
              prompt: "Listen and tap the word you hear",
              audio: "トマト",
              options: ["トマト", "タコ", "ナイフ", "テスト"],
              answer: "トマト",
            },
            {
              type: "match-pairs",
              prompt: "Match each katakana character to its sound",
              pairs: [
                { left: "チ", right: "chi" },
                { left: "ヌ", right: "nu" },
                { left: "ノ", right: "no" },
                { left: "フ", right: "fu" },
              ],
            },
            {
              type: "translate-choice",
              prompt: "シ or ツ — which one is 'tsu'?",
              display: "❓",
              options: ["ツ", "シ", "ソ", "ン"],
              answer: "ツ",
              note: "シ sweeps up-and-right; ツ sweeps down-and-left.",
            },
            {
              type: "build-sentence",
              prompt: "Build 'tuna' (tsuna)",
              display: "tuna",
              tiles: ["ツ", "ナ"],
              answer: ["ツ", "ナ"],
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "ネコ",
              answer: "neko",
              accept: ["neco"],
            },
          ],
        },
        {
          id: "u6-katakana-m-y-r-w",
          title: "Katakana: M, Y, R & W",
          subtitle: "マ行　ヤ行　ラ行　ワ・ヲ・ン",
          icon: "ラ",
          skill: "reading",
          xp: 30,
          teach: [
            {
              char: "マ",
              romaji: "ma",
              mnemonic: "マ keeps ま's cross-stroke and hook, angled instead of curved.",
              mnemonicEmoji: "👩",
              example: { word: "ママ", romaji: "mama", meaning: "mom (casual)" },
            },
            {
              char: "ミ",
              romaji: "mi",
              mnemonic: "ミ is three short parallel strokes — み's tail, simplified into a clean stack.",
              mnemonicEmoji: "🥛",
              example: { word: "ミルク", romaji: "miruku", meaning: "milk" },
            },
            {
              char: "ム",
              romaji: "mu",
              mnemonic: "ム is two crossing strokes — む's loop, opened into an angle.",
              mnemonicEmoji: "🏘️",
              example: { word: "ムラ", romaji: "mura", meaning: "village" },
            },
            {
              char: "メ",
              romaji: "me",
              mnemonic: "メ is ノ's single stroke plus a second stroke crossing it — that's the whole difference from ノ.",
              mnemonicEmoji: "👓",
              example: { word: "メガネ", romaji: "megane", meaning: "glasses" },
              contrast: {
                label: "Don't mix up with ノ",
                a: { word: "ノ", romaji: "no", meaning: "single stroke only (last lesson)" },
                b: { word: "メ", romaji: "me", meaning: "adds a second crossing stroke" },
              },
            },
            {
              char: "モ",
              romaji: "mo",
              mnemonic: "モ keeps も's cross-stroke and hook, straightened.",
              mnemonicEmoji: "🍑",
              example: { word: "モモ", romaji: "momo", meaning: "peach" },
            },
            {
              char: "ヤ",
              romaji: "ya",
              mnemonic: "ヤ is や's shape with the curve straightened into an angle.",
              mnemonicEmoji: "⛰️",
              example: { word: "ヤマ", romaji: "yama", meaning: "mountain" },
            },
            {
              char: "ユ",
              romaji: "yu",
              mnemonic: "ユ is ゆ's hook, opened into two straight strokes.",
              mnemonicEmoji: "❄️",
              example: { word: "ユキ", romaji: "yuki", meaning: "snow (also a name — this is your AI tutor's name)" },
            },
            {
              char: "ヨ",
              romaji: "yo",
              mnemonic: "ヨ is よ's three strokes, squared into a compact shape.",
              mnemonicEmoji: "🧘",
              example: { word: "ヨガ", romaji: "yoga", meaning: "yoga" },
            },
            {
              char: "ラ",
              romaji: "ra",
              mnemonic: "ラ is ら's shape with the curve straightened.",
              mnemonicEmoji: "📻",
              example: { word: "ラジオ", romaji: "rajio", meaning: "radio" },
            },
            {
              char: "リ",
              romaji: "ri",
              mnemonic: "リ is two short vertical strokes — り stripped to the bone.",
              mnemonicEmoji: "🐿️",
              example: { word: "リス", romaji: "risu", meaning: "squirrel" },
            },
            {
              char: "ル",
              romaji: "ru",
              mnemonic: "ル keeps る's loop at the end but straightens the lead-in stroke.",
              mnemonicEmoji: "🚗",
              example: { word: "クルマ", romaji: "kuruma", meaning: "car" },
            },
            {
              char: "レ",
              romaji: "re",
              mnemonic: "レ is a single stroke that drops then kicks right — れ's shape, angled.",
              mnemonicEmoji: "🚻",
              example: { word: "トイレ", romaji: "toire", meaning: "toilet" },
            },
            {
              char: "ロ",
              romaji: "ro",
              mnemonic: "ロ is a plain square — ろ's loop, closed into a box.",
              mnemonicEmoji: "🤖",
              example: { word: "ロボット", romaji: "robotto", meaning: "robot" },
            },
            {
              char: "ワ",
              romaji: "wa",
              mnemonic: "ワ keeps わ's overall shape but straightens the curl.",
              mnemonicEmoji: "🐊",
              example: { word: "ワニ", romaji: "wani", meaning: "crocodile" },
            },
            {
              char: "ヲ",
              romaji: "wo",
              mnemonic: "ヲ almost never starts a real word — in real writing the object-marker を (always hiragana) is what you'll actually meet. ヲ exists, but you may go your whole trip without seeing it outside a dictionary.",
              mnemonicEmoji: "🈳",
              example: { word: "ヲ", romaji: "wo", meaning: "the object-marker particle, in its rare katakana form" },
            },
            {
              char: "ン",
              romaji: "n",
              mnemonic: "ン is two short strokes, the top one short and near-horizontal, sitting lower than ソ's steep, high stroke.",
              mnemonicEmoji: "🔘",
              example: { word: "ボタン", romaji: "botan", meaning: "button" },
              contrast: {
                label: "Don't mix up with ソ",
                a: { word: "ソ", romaji: "so", meaning: "top stroke steep, starts high (first lesson)" },
                b: { word: "ン", romaji: "n", meaning: "top stroke short & near-horizontal, sits low" },
              },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "ソ or ン — which one is 'n'?",
              display: "❓",
              options: ["ン", "ソ", "ノ", "メ"],
              answer: "ン",
              note: "ソ's top stroke is steep and starts high; ン's is short and sits low.",
            },
            {
              type: "translate-choice",
              prompt: "ノ or メ — which one is 'me'?",
              display: "❓",
              options: ["メ", "ノ", "ム", "モ"],
              answer: "メ",
              note: "メ is ノ plus a second crossing stroke.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "クルマ",
              answer: "kuruma",
              note: "'Car'.",
            },
            {
              type: "listen-choice",
              prompt: "Listen and tap the word you hear",
              audio: "トイレ",
              options: ["トイレ", "ラジオ", "ロボット", "ミルク"],
              answer: "トイレ",
              note: "Worth memorizing this one above all the others this lesson.",
            },
            {
              type: "match-pairs",
              prompt: "Match each katakana character to its sound",
              pairs: [
                { left: "ヤ", right: "ya" },
                { left: "リ", right: "ri" },
                { left: "ム", right: "mu" },
                { left: "ワ", right: "wa" },
              ],
            },
            {
              type: "category-sort",
              prompt: "Sort: single stroke vs crossing strokes",
              categories: ["1画 (one stroke)", "交差 (crossing strokes)"],
              items: [
                { label: "ノ", romaji: "no", category: "1画 (one stroke)" },
                { label: "メ", romaji: "me", category: "交差 (crossing strokes)" },
                { label: "ン", romaji: "n", category: "交差 (crossing strokes)" },
                { label: "ソ", romaji: "so", category: "交差 (crossing strokes)" },
              ],
              note: "ノ really is a single stroke — everything else in this lesson's lookalike traps has two.",
            },
            {
              type: "build-sentence",
              prompt: "Build 'button' (botan)",
              display: "button",
              tiles: ["ボ", "タ", "ン"],
              answer: ["ボ", "タ", "ン"],
              note: "ボ isn't taught until next lesson — this previews it. You've got the sound already from ホ + ゛.",
            },
          ],
        },
        {
          id: "u6-katakana-voiced-combo",
          title: "Katakana: Voiced & Combo Sounds",
          subtitle: "ガ行　ザ行　ダ行　バ行　パ行　きゃ・しゅ・ちょ",
          icon: "゛",
          skill: "reading",
          xp: 30,
          teach: [
            {
              char: "ガ",
              romaji: "ga",
              mnemonic: "カ + ゛ = ガ. Same dakuten rule you already know from hiragana: ka → ga.",
              mnemonicEmoji: "゛",
              example: { word: "ガム", romaji: "gamu", meaning: "gum" },
              contrast: {
                a: { word: "カ", romaji: "ka", meaning: "plain" },
                b: { word: "ガ", romaji: "ga", meaning: "voiced ゛" },
              },
            },
            {
              char: "ゴ",
              romaji: "go",
              mnemonic: "コ + ゛ = ゴ. ko → go.",
              mnemonicEmoji: "゛",
              example: { word: "ゴミ", romaji: "gomi", meaning: "trash" },
              contrast: {
                a: { word: "コ", romaji: "ko", meaning: "plain" },
                b: { word: "ゴ", romaji: "go", meaning: "voiced ゛" },
              },
            },
            {
              char: "ザ",
              romaji: "za",
              mnemonic: "サ + ゛ = ザ. sa → za.",
              mnemonicEmoji: "゛",
              example: { word: "ピザ", romaji: "piza", meaning: "pizza" },
              contrast: {
                a: { word: "サ", romaji: "sa", meaning: "plain" },
                b: { word: "ザ", romaji: "za", meaning: "voiced ゛" },
              },
            },
            {
              char: "ジ",
              romaji: "ji",
              mnemonic: "シ + ゛ = ジ. shi → ji (not 'zi') — same exception as hiragana's し→じ.",
              mnemonicEmoji: "゛",
              example: { word: "レジ", romaji: "reji", meaning: "cash register / checkout" },
              contrast: {
                a: { word: "シ", romaji: "shi", meaning: "plain" },
                b: { word: "ジ", romaji: "ji", meaning: "voiced ゛" },
              },
            },
            {
              char: "ダ",
              romaji: "da",
              mnemonic: "タ + ゛ = ダ. ta → da.",
              mnemonicEmoji: "゛",
              example: { word: "サラダ", romaji: "sarada", meaning: "salad" },
              contrast: {
                a: { word: "タ", romaji: "ta", meaning: "plain" },
                b: { word: "ダ", romaji: "da", meaning: "voiced ゛" },
              },
            },
            {
              char: "ド",
              romaji: "do",
              mnemonic: "ト + ゛ = ド. to → do.",
              mnemonicEmoji: "゛",
              example: { word: "ドア", romaji: "doa", meaning: "door" },
              contrast: {
                a: { word: "ト", romaji: "to", meaning: "plain" },
                b: { word: "ド", romaji: "do", meaning: "voiced ゛" },
              },
            },
            {
              char: "バ",
              romaji: "ba",
              mnemonic: "ハ + ゛ = バ. ha → ba.",
              mnemonicEmoji: "゛",
              example: { word: "バス", romaji: "basu", meaning: "bus" },
              contrast: {
                a: { word: "ハ", romaji: "ha", meaning: "plain" },
                b: { word: "バ", romaji: "ba", meaning: "voiced ゛" },
              },
            },
            {
              char: "ボ",
              romaji: "bo",
              mnemonic: "ホ + ゛ = ボ. ho → bo.",
              mnemonicEmoji: "゛",
              example: { word: "ボウシ", romaji: "boushi", meaning: "hat" },
              contrast: {
                a: { word: "ホ", romaji: "ho", meaning: "plain" },
                b: { word: "ボ", romaji: "bo", meaning: "voiced ゛" },
              },
            },
            {
              char: "パ",
              romaji: "pa",
              mnemonic: "ハ + ゜ = パ. You already met this exact word in hiragana as ぱん — 'bread' is a loanword (Portuguese pão), so パン is how it's actually written in Japan.",
              mnemonicEmoji: "゜",
              example: { word: "パン", romaji: "pan", meaning: "bread" },
              contrast: {
                a: { word: "ハ", romaji: "ha", meaning: "plain" },
                b: { word: "パ", romaji: "pa", meaning: "with ゜ (p)" },
              },
            },
            {
              char: "ピ",
              romaji: "pi",
              mnemonic: "ヒ + ゜ = ピ. hi → pi.",
              mnemonicEmoji: "゜",
              example: { word: "ピアノ", romaji: "piano", meaning: "piano" },
              contrast: {
                a: { word: "ヒ", romaji: "hi", meaning: "plain" },
                b: { word: "ピ", romaji: "pi", meaning: "with ゜ (p)" },
              },
            },
            {
              char: "プ",
              romaji: "pu",
              mnemonic: "フ + ゜ = プ. fu → pu.",
              mnemonicEmoji: "゜",
              example: { word: "プリン", romaji: "purin", meaning: "custard pudding" },
              contrast: {
                a: { word: "フ", romaji: "fu", meaning: "plain" },
                b: { word: "プ", romaji: "pu", meaning: "with ゜ (p)" },
              },
            },
            {
              char: "ペ",
              romaji: "pe",
              mnemonic: "ヘ + ゜ = ペ. he → pe.",
              mnemonicEmoji: "゜",
              example: { word: "ペン", romaji: "pen", meaning: "pen" },
              contrast: {
                a: { word: "ヘ", romaji: "he", meaning: "plain" },
                b: { word: "ペ", romaji: "pe", meaning: "with ゜ (p)" },
              },
            },
            {
              char: "ポ",
              romaji: "po",
              mnemonic: "ホ + ゜ = ポ. ho → po.",
              mnemonicEmoji: "゜",
              example: { word: "ポスト", romaji: "posuto", meaning: "mailbox" },
              contrast: {
                a: { word: "ホ", romaji: "ho", meaning: "plain" },
                b: { word: "ポ", romaji: "po", meaning: "with ゜ (p)" },
              },
            },
            {
              char: "キャ",
              romaji: "kya",
              mnemonic: "キ + small ャ glides into one syllable: ki-ya slurred together, same as hiragana きゃ.",
              mnemonicEmoji: "⛺",
              example: { word: "キャンプ", romaji: "kyanpu", meaning: "camp" },
            },
            {
              char: "シュ",
              romaji: "shu",
              mnemonic: "シ + small ュ = shu, one syllable. You'll see this constantly in loanwords with ー right after it — that's next lesson.",
              mnemonicEmoji: "👟",
              example: { word: "シューズ", romaji: "shuuzu", meaning: "shoes" },
            },
            {
              char: "チョ",
              romaji: "cho",
              mnemonic: "チ + small ョ = cho, one syllable.",
              mnemonicEmoji: "🍫",
              example: { word: "チョコ", romaji: "choko", meaning: "chocolate (short for チョコレート)" },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "ハ + ゛ makes which sound?",
              display: "バ",
              options: ["ba", "ha", "pa", "da"],
              answer: "ba",
              note: "Same dakuten rule as hiragana: two dashes voices the consonant.",
            },
            {
              type: "translate-choice",
              prompt: "ハ + ゜ makes which sound?",
              display: "パ",
              options: ["pa", "ba", "ha", "pi"],
              answer: "pa",
              note: "゛= b, ゜= p — only the h-row takes both.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "サラダ",
              answer: "sarada",
              note: "'Salad'.",
            },
            {
              type: "listen-choice",
              prompt: "Listen: voiced or not?",
              audio: "ゴ",
              options: ["ゴ", "コ", "ゾ", "ギ"],
              answer: "ゴ",
            },
            {
              type: "match-pairs",
              prompt: "Match the voiced/combo character to its sound",
              pairs: [
                { left: "ジ", right: "ji" },
                { left: "プ", right: "pu" },
                { left: "キャ", right: "kya" },
                { left: "チョ", right: "cho" },
              ],
            },
            {
              type: "category-sort",
              prompt: "Sort by mark",
              categories: ["゛ (b/g/z/d)", "゜ (p)"],
              items: [
                { label: "ガ", romaji: "ga", category: "゛ (b/g/z/d)" },
                { label: "ザ", romaji: "za", category: "゛ (b/g/z/d)" },
                { label: "パ", romaji: "pa", category: "゜ (p)" },
                { label: "ポ", romaji: "po", category: "゜ (p)" },
              ],
            },
            {
              type: "build-sentence",
              prompt: "Build 'bread' (pan) — the real way it's written",
              display: "bread (the real written form)",
              tiles: ["パ", "ン"],
              answer: ["パ", "ン"],
              note: "You met this word first as hiragana ぱん. パン is how bakeries in Japan actually write it.",
            },
          ],
        },
        {
          id: "u6-katakana-long-vowel",
          title: "Katakana: The Long Vowel Mark",
          subtitle: "ー — the mark you already know, in new words",
          icon: "ー",
          skill: "reading",
          xp: 25,
          teach: [
            {
              kind: "phrase",
              term: "ー",
              reading: "(long)",
              meaning: "Holds the previous vowel one beat longer",
              note: "You already met this exact mark back in Unit 1 (Small っ & Long Vowels) — おおきい held its vowel by doubling it (hiragana's way). ー is katakana's way: same job, different notation. Never a hyphen, never skippable — dropping it either breaks the word or turns it into a different one.",
              context: "Almost every katakana word with a drawn-out vowel sound uses it — loanwords especially.",
            },
            {
              kind: "phrase",
              term: "ラーメン",
              reading: "raamen",
              meaning: "ramen",
              context: "On every restaurant sign and menu you'll see in Japan.",
              contrast: {
                label: "ー is not optional",
                a: { word: "ラーメン", romaji: "raamen", meaning: "ramen — the real word" },
                b: { word: "ラメン", romaji: "ramen", meaning: "not a real word — a common mis-hearing if you drop the ー" },
              },
            },
            {
              kind: "phrase",
              term: "コーヒー",
              reading: "koohii",
              meaning: "coffee",
              context: "Has TWO long vowels — say both, or it stops sounding like the word.",
              contrast: {
                label: "ー is not optional",
                a: { word: "コーヒー", romaji: "koohii", meaning: "coffee — the real word" },
                b: { word: "コヒー", romaji: "kohii", meaning: "not a real word if you drop either ー" },
              },
            },
            {
              kind: "phrase",
              term: "ビール",
              reading: "biiru",
              meaning: "beer",
              context: "The sharpest example of why ー matters: drop it, and it's not just wrong, it's a DIFFERENT real word.",
              contrast: {
                label: "Two different real words",
                a: { word: "ビール", romaji: "biiru", meaning: "beer" },
                b: { word: "ビル", romaji: "biru", meaning: "building — a completely different word, not a typo of the first" },
              },
            },
            {
              kind: "phrase",
              term: "タクシー",
              reading: "takushii",
              meaning: "taxi",
              context: "All the shapes here were already taught in earlier lessons — this word just needed ー to be spelled correctly.",
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which is the real word for 'ramen'?",
              display: "❓",
              options: ["ラーメン", "ラメン", "ラーメソ", "ラアメン"],
              answer: "ラーメン",
              note: "Drop the ー and it's not a real word.",
            },
            {
              type: "translate-choice",
              prompt: "ビール and ビル — which one is 'building'?",
              display: "❓",
              options: ["ビル", "ビール", "both", "neither"],
              answer: "ビル",
              note: "ビール (long) is beer. ビル (short) is a completely different word: building.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "コーヒー",
              answer: "koohii",
              accept: ["kohii", "koffee", "kōhī"],
              note: "Two long vowels — say both.",
            },
            {
              type: "listen-choice",
              prompt: "Listen and tap the word you hear",
              audio: "タクシー",
              options: ["タクシー", "ラーメン", "ビール", "コーヒー"],
              answer: "タクシー",
            },
            {
              type: "match-pairs",
              prompt: "Match each word to its meaning",
              pairs: [
                { left: "ラーメン", right: "ramen" },
                { left: "コーヒー", right: "coffee" },
                { left: "ビール", right: "beer" },
                { left: "タクシー", right: "taxi" },
              ],
            },
            {
              type: "build-sentence",
              prompt: "Build 'coffee' (koohii)",
              display: "coffee",
              tiles: ["コ", "ー", "ヒ", "ー"],
              answer: ["コ", "ー", "ヒ", "ー"],
            },
          ],
        },
        {
          id: "u6-checkpoint",
          title: "Dojo Checkpoint",
          subtitle: "Katakana — prove it",
          icon: "⛩️",
          skill: "reading",
          xp: 45,
          checkpoint: true,
          exercises: [
            {
              type: "category-sort",
              prompt: "Sort: hiragana vs katakana",
              categories: ["ひらがな", "カタカナ"],
              items: [
                { label: "め", romaji: "me", category: "ひらがな" },
                { label: "メ", romaji: "me", category: "カタカナ" },
                { label: "の", romaji: "no", category: "ひらがな" },
                { label: "ノ", romaji: "no", category: "カタカナ" },
              ],
            },
            {
              type: "translate-choice",
              prompt: "シ, ツ, ソ or ン — which one is 'shi'?",
              display: "❓",
              options: ["シ", "ツ", "ソ", "ン"],
              answer: "シ",
              note: "Bottom stroke sweeps up-and-right.",
            },
            {
              type: "listen-choice",
              prompt: "Listen: which did you hear?",
              audio: "トイレ",
              options: ["toire", "toilet", "torire", "toile"],
              answer: "toire",
            },
            {
              type: "match-pairs",
              prompt: "Match each loanword to its meaning",
              pairs: [
                { left: "ホテル", right: "hotel" },
                { left: "バス", right: "bus" },
                { left: "サラダ", right: "salad" },
                { left: "ビール", right: "beer" },
              ],
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this word",
              display: "レストラン",
              answer: "resutoran",
              note: "'Restaurant' — every shape here was taught this unit.",
            },
            {
              type: "build-sentence",
              prompt: "Build 'taxi' (takushii)",
              display: "taxi",
              tiles: ["タ", "ク", "シ", "ー"],
              answer: ["タ", "ク", "シ", "ー"],
              note: "The final ー isn't optional — drop it and you've said something else.",
            },
            {
              type: "translate-choice",
              prompt: "Which pair are two DIFFERENT real words, not a typo?",
              display: "❓",
              options: ["ビール / ビル", "ラーメン / ラメン", "コーヒー / コヒー", "タクシー / タクシ"],
              answer: "ビール / ビル",
              note: "Beer vs. building — everything else in this list is a real word vs. a mistake.",
            },
          ],
        },
      ],
    },
  ],
};
