import type { Level } from "@/lib/types";

// Beginner level — fully authored, kana + romaji (no raw kanji this stage).
// Five units spanning the four skills, getting harder as the learner advances.
export const beginner: Level = {
  id: "beginner",
  title: "Beginner",
  blurb: "Hiragana, greetings, numbers, nouns & adjectives.",
  units: [
    // ===== UNIT 1: Hiragana Foundations ====================================
    {
      id: "u1-hiragana",
      title: "Hiragana Foundations",
      subtitle: "Your first characters & sounds",
      lessons: [
        {
          id: "u1-vowels",
          title: "The 5 Vowels",
          subtitle: "あ い う え お",
          icon: "あ",
          skill: "writing",
          xp: 20,
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "あ",
              options: ["a", "i", "u", "e"],
              answer: "a",
              note: "あ is pronounced like the 'a' in 'father'.",
            },
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "い",
              options: ["o", "e", "i", "a"],
              answer: "i",
              note: "い sounds like the 'ee' in 'see'.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this character",
              display: "う",
              answer: "u",
              note: "う sounds like the 'oo' in 'food'.",
            },
            {
              type: "match-pairs",
              prompt: "Match each character to its sound",
              pairs: [
                { left: "え", right: "e" },
                { left: "お", right: "o" },
                { left: "あ", right: "a" },
              ],
              note: "The five vowels are the foundation of every kana.",
            },
          ],
        },
        {
          id: "u1-ka-row",
          title: "The K-row",
          subtitle: "か き く け こ",
          icon: "か",
          skill: "writing",
          xp: 20,
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "か",
              options: ["ka", "ki", "ku", "ko"],
              answer: "ka",
              note: "か = k + a.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this character",
              display: "き",
              answer: "ki",
              note: "き = k + i.",
            },
            {
              type: "match-pairs",
              prompt: "Match each character to its sound",
              pairs: [
                { left: "く", right: "ku" },
                { left: "け", right: "ke" },
                { left: "こ", right: "ko" },
              ],
              note: "Notice the pattern: consonant + vowel.",
            },
          ],
        },
        {
          id: "u1-row-sort",
          title: "Sort the Rows",
          subtitle: "Vowels vs K-row",
          icon: "🗂️",
          skill: "writing",
          xp: 25,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each kana into its row",
              categories: ["Vowels (a/i/u…)", "K-row (ka/ki…)"],
              items: [
                { label: "あ", romaji: "a", category: "Vowels (a/i/u…)" },
                { label: "い", romaji: "i", category: "Vowels (a/i/u…)" },
                { label: "う", romaji: "u", category: "Vowels (a/i/u…)" },
                { label: "か", romaji: "ka", category: "K-row (ka/ki…)" },
                { label: "き", romaji: "ki", category: "K-row (ka/ki…)" },
                { label: "く", romaji: "ku", category: "K-row (ka/ki…)" },
              ],
              note: "Every K-row kana is just k + a vowel sound.",
            },
          ],
        },
        {
          id: "u1-listen",
          title: "Hear the Kana",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 25,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Tap play and pick the sound you hear",
              audio: "あ",
              options: ["a", "e", "o", "u"],
              answer: "a",
              note: "Train your ear before your eyes — listen first.",
            },
            {
              type: "listen-choice",
              prompt: "Tap play and pick the sound you hear",
              audio: "き",
              options: ["ka", "ki", "ke", "ku"],
              answer: "ki",
              note: "き sounds like 'key'.",
            },
            {
              type: "listen-choice",
              prompt: "Tap play and pick the sound you hear",
              audio: "こ",
              options: ["ko", "ka", "ku", "ke"],
              answer: "ko",
              note: "こ sounds like 'co' in 'cocoa'.",
            },
          ],
        },
        {
          id: "u1-speak",
          title: "Say the Kana",
          subtitle: "Speaking drill",
          icon: "🗣️",
          skill: "speaking",
          xp: 25,
          exercises: [
            {
              type: "speak-phrase",
              prompt: "Say this sound aloud",
              display: "あ",
              romaji: "a",
              accept: ["a", "ah", "あー"],
              note: "Open your mouth wide — a clear 'ah'.",
            },
            {
              type: "speak-phrase",
              prompt: "Say this sound aloud",
              display: "か",
              romaji: "ka",
              accept: ["ka", "car"],
              note: "か — a crisp 'ka'.",
            },
            {
              type: "speak-phrase",
              prompt: "Say this sound aloud",
              display: "こ",
              romaji: "ko",
              accept: ["ko", "co"],
              note: "こ — like 'co' in 'cocoa'.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 2: Greetings & Self-Introduction ===========================
    {
      id: "u2-greetings",
      title: "Greetings & Self-Intro",
      subtitle: "Hello, thanks & your name",
      lessons: [
        {
          id: "u2-greetings-core",
          title: "Basic Greetings",
          subtitle: "Say hello & thanks",
          icon: "👋",
          skill: "writing",
          xp: 25,
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the greeting to its meaning",
              pairs: [
                { left: "おはよう", right: "Good morning" },
                { left: "こんにちは", right: "Hello (daytime)" },
                { left: "こんばんは", right: "Good evening" },
                { left: "ありがとう", right: "Thank you" },
              ],
              note: "は in greetings is pronounced 'wa'.",
            },
            {
              type: "translate-choice",
              prompt: "What do you say in the evening?",
              display: "🌙",
              options: ["おはよう", "こんにちは", "こんばんは", "ありがとう"],
              answer: "こんばんは",
              note: "こんばんは (konbanwa) — good evening.",
            },
            {
              type: "type-answer",
              prompt: "How do you say 'Good morning'? (romaji)",
              display: "おはよう",
              answer: "ohayou",
              accept: ["ohayo"],
              note: "おはよう (ohayou) — add ございます to be polite.",
            },
          ],
        },
        {
          id: "u2-self-intro",
          title: "Introducing Yourself",
          subtitle: "Name & nice to meet you",
          icon: "🙋",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "translate-choice",
              prompt: "Select the meaning",
              display: "はじめまして",
              options: [
                "Nice to meet you",
                "See you later",
                "I'm sorry",
                "Excuse me",
              ],
              answer: "Nice to meet you",
              note: "はじめまして (hajimemashite) opens a first meeting.",
            },
            {
              type: "build-sentence",
              prompt: "Build: 'I am Tanaka' (watashi wa Tanaka desu)",
              display: "I am Tanaka",
              tiles: ["わたし", "は", "たなか", "です"],
              answer: ["わたし", "は", "たなか", "です"],
              note: "わたしは X です = 'I am X'. Polite and simple.",
            },
            {
              type: "match-pairs",
              prompt: "Match the phrase to its meaning",
              pairs: [
                { left: "よろしく", right: "Please be kind to me" },
                { left: "すみません", right: "Excuse me / Sorry" },
              ],
              note: "よろしく often follows your introduction.",
            },
          ],
        },
        {
          id: "u2-listen",
          title: "Which Greeting?",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 30,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Which greeting did you hear?",
              audio: "こんにちは",
              options: ["Hello", "Good evening", "Thank you", "Goodbye"],
              answer: "Hello",
              note: "こんにちは — the daytime hello.",
            },
            {
              type: "listen-choice",
              prompt: "What did you hear?",
              audio: "はじめまして",
              options: ["Nice to meet you", "Goodbye", "Thank you", "Excuse me"],
              answer: "Nice to meet you",
              note: "はじめまして opens a first meeting.",
            },
          ],
        },
        {
          id: "u2-speak",
          title: "Greet Out Loud",
          subtitle: "Speaking drill",
          icon: "🗣️",
          skill: "speaking",
          xp: 30,
          exercises: [
            {
              type: "speak-phrase",
              prompt: "Say 'Hello'",
              display: "こんにちは",
              romaji: "konnichiwa",
              accept: ["こんにちわ", "konnichiwa", "konnichwa"],
              note: "Written こんにちは, said 'konnichiwa'.",
            },
            {
              type: "speak-phrase",
              prompt: "Say 'Thank you'",
              display: "ありがとう",
              romaji: "arigatou",
              accept: ["ありがとうございます", "arigato", "arigatou"],
              note: "Add ございます to sound more polite.",
            },
          ],
        },
        {
          id: "u2-punctuation",
          title: "Punctuation Dojo",
          subtitle: "。 、 「」 ー っ",
          icon: "。",
          skill: "punctuation",
          xp: 30,
          exercises: [
            {
              type: "translate-choice",
              prompt: "What is 。 used for?",
              display: "。",
              options: [
                "End of a sentence (full stop)",
                "A comma / pause",
                "A question",
                "A long vowel",
              ],
              answer: "End of a sentence (full stop)",
              note: "。 (maru) is the Japanese full stop.",
            },
            {
              type: "translate-choice",
              prompt: "The small っ doubles a consonant. How is がっこう read?",
              display: "がっこう",
              options: ["gakkou (double k)", "gako", "gatsukou", "ga-ko-u"],
              answer: "gakkou (double k)",
              note: "Small っ (sokuon) doubles the next consonant: gak-kou.",
            },
            {
              type: "build-sentence",
              prompt: "Build 'Hello.' with the right full stop",
              display: "Hello.",
              tiles: ["こんにちは", "。"],
              answer: ["こんにちは", "。"],
              note: "Statements end with 。 — don't forget it.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 3: Numbers, Age & Time =====================================
    {
      id: "u3-numbers",
      title: "Numbers, Age & Time",
      subtitle: "Count, say your age & ask the time",
      lessons: [
        {
          id: "u3-numbers-1-10",
          title: "Numbers 1–10",
          subtitle: "いち に さん …",
          icon: "🔢",
          skill: "writing",
          xp: 25,
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the number to its digit",
              pairs: [
                { left: "いち", right: "1" },
                { left: "に", right: "2" },
                { left: "さん", right: "3" },
                { left: "ご", right: "5" },
              ],
              note: "1=いち, 2=に, 3=さん, 4=よん, 5=ご.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for 7 (なな)",
              display: "なな",
              answer: "nana",
              accept: ["shichi", "しち", "nana"],
              note: "7 is なな (nana) or しち (shichi).",
            },
          ],
        },
        {
          id: "u3-number-sort",
          title: "Sort the Numbers",
          subtitle: "1–5 vs 6–10",
          icon: "🗂️",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each number into the right range",
              categories: ["1–5", "6–10"],
              items: [
                { label: "いち", romaji: "1", category: "1–5" },
                { label: "さん", romaji: "3", category: "1–5" },
                { label: "ご", romaji: "5", category: "1–5" },
                { label: "なな", romaji: "7", category: "6–10" },
                { label: "はち", romaji: "8", category: "6–10" },
                { label: "じゅう", romaji: "10", category: "6–10" },
              ],
              note: "6=ろく, 7=なな, 8=はち, 9=きゅう, 10=じゅう.",
            },
          ],
        },
        {
          id: "u3-age-time",
          title: "Age & Asking the Time",
          subtitle: "〜さい です",
          icon: "⏰",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "build-sentence",
              prompt: "Build: 'I am 5 years old' (watashi wa go-sai desu)",
              display: "I am 5 years old",
              tiles: ["わたし", "は", "ご", "さい", "です"],
              answer: ["わたし", "は", "ご", "さい", "です"],
              note: "〜さい (sai) = the 'years old' counter.",
            },
            {
              type: "match-pairs",
              prompt: "Match the question to its meaning",
              pairs: [
                { left: "なんさいですか", right: "How old are you?" },
                { left: "いまなんじですか", right: "What time is it?" },
              ],
              note: "なん (nan) = 'what / how many'.",
            },
          ],
        },
        {
          id: "u3-listen",
          title: "Hear the Number",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 30,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Which number did you hear?",
              audio: "さん",
              options: ["1", "3", "5", "8"],
              answer: "3",
              note: "さん (san) = 3.",
            },
            {
              type: "listen-choice",
              prompt: "Which number did you hear?",
              audio: "じゅう",
              options: ["6", "7", "9", "10"],
              answer: "10",
              note: "じゅう (juu) = 10.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 4: Essential Nouns & Categorising ==========================
    {
      id: "u4-nouns",
      title: "Nouns & Categorising",
      subtitle: "People, things & food",
      lessons: [
        {
          id: "u4-family",
          title: "Family & People",
          subtitle: "おかあさん おとうさん …",
          icon: "👪",
          skill: "writing",
          xp: 25,
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the word to its meaning",
              pairs: [
                { left: "おかあさん", right: "mother" },
                { left: "おとうさん", right: "father" },
                { left: "あに", right: "older brother" },
                { left: "いもうと", right: "younger sister" },
              ],
              note: "Family words often start with お as politeness.",
            },
          ],
        },
        {
          id: "u4-people-things",
          title: "People vs Things",
          subtitle: "Sorting game",
          icon: "🗂️",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each word: a person or a thing?",
              categories: ["ひと (people)", "もの (things)"],
              items: [
                { label: "おかあさん", romaji: "okaasan", category: "ひと (people)" },
                { label: "おとうさん", romaji: "otousan", category: "ひと (people)" },
                { label: "せんせい", romaji: "sensei", category: "ひと (people)" },
                { label: "ほん", romaji: "hon (book)", category: "もの (things)" },
                { label: "くるま", romaji: "kuruma (car)", category: "もの (things)" },
                { label: "でんわ", romaji: "denwa (phone)", category: "もの (things)" },
              ],
              note: "せんせい (sensei) = teacher.",
            },
          ],
        },
        {
          id: "u4-food-objects",
          title: "Food vs Objects",
          subtitle: "Sorting game",
          icon: "🍙",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each word: food or object?",
              categories: ["たべもの (food)", "もの (objects)"],
              items: [
                { label: "ごはん", romaji: "gohan (rice)", category: "たべもの (food)" },
                { label: "さかな", romaji: "sakana (fish)", category: "たべもの (food)" },
                { label: "りんご", romaji: "ringo (apple)", category: "たべもの (food)" },
                { label: "やさい", romaji: "yasai (veg)", category: "たべもの (food)" },
                { label: "いえ", romaji: "ie (house)", category: "もの (objects)" },
                { label: "でんわ", romaji: "denwa (phone)", category: "もの (objects)" },
              ],
              note: "ごはん means both 'rice' and 'a meal'.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for 'apple' (りんご)",
              display: "りんご",
              answer: "ringo",
              note: "りんご (ringo) = apple.",
            },
          ],
        },
        {
          id: "u4-listen",
          title: "Hear the Noun",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 30,
          exercises: [
            {
              type: "listen-choice",
              prompt: "What did you hear?",
              audio: "ごはん",
              options: ["rice / meal", "car", "phone", "fish"],
              answer: "rice / meal",
              note: "ごはん (gohan).",
            },
            {
              type: "listen-choice",
              prompt: "What did you hear?",
              audio: "くるま",
              options: ["house", "car", "book", "apple"],
              answer: "car",
              note: "くるま (kuruma) = car.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 5: Adjectives & Descriptions ===============================
    {
      id: "u5-adjectives",
      title: "Adjectives & Descriptions",
      subtitle: "Describe things around you",
      lessons: [
        {
          id: "u5-size-temp",
          title: "Big/Small, Hot/Cold",
          subtitle: "おおきい ちいさい …",
          icon: "📏",
          skill: "writing",
          xp: 25,
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the adjective to its meaning",
              pairs: [
                { left: "おおきい", right: "big" },
                { left: "ちいさい", right: "small" },
                { left: "あつい", right: "hot" },
                { left: "さむい", right: "cold" },
              ],
              note: "Most basic adjectives end in い.",
            },
            {
              type: "build-sentence",
              prompt: "Build: 'This book is big' (kono hon wa ookii desu)",
              display: "This book is big",
              tiles: ["この", "ほん", "は", "おおきい", "です"],
              answer: ["この", "ほん", "は", "おおきい", "です"],
              note: "この X は ... です = 'This X is ...'.",
            },
          ],
        },
        {
          id: "u5-sort",
          title: "Size vs Temperature",
          subtitle: "Sorting game",
          icon: "🗂️",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each adjective by what it describes",
              categories: ["size", "temperature"],
              items: [
                { label: "おおきい", romaji: "ookii (big)", category: "size" },
                { label: "ちいさい", romaji: "chiisai (small)", category: "size" },
                { label: "あつい", romaji: "atsui (hot)", category: "temperature" },
                { label: "さむい", romaji: "samui (cold)", category: "temperature" },
              ],
              note: "あつい can mean hot weather or a hot object.",
            },
          ],
        },
        {
          id: "u5-positive-negative",
          title: "Good vs Bad",
          subtitle: "Sorting game",
          icon: "⚖️",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each word: positive or negative?",
              categories: ["positive", "negative"],
              items: [
                { label: "おいしい", romaji: "oishii (tasty)", category: "positive" },
                { label: "いい", romaji: "ii (good)", category: "positive" },
                { label: "あたらしい", romaji: "atarashii (new)", category: "positive" },
                { label: "まずい", romaji: "mazui (bad taste)", category: "negative" },
                { label: "わるい", romaji: "warui (bad)", category: "negative" },
                { label: "ふるい", romaji: "furui (old)", category: "negative" },
              ],
              note: "Context matters — 'old' isn't always negative!",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for 'delicious' (おいしい)",
              display: "おいしい",
              answer: "oishii",
              accept: ["oishi"],
              note: "おいしい (oishii) = delicious.",
            },
          ],
        },
        {
          id: "u5-speak",
          title: "Describe It Out Loud",
          subtitle: "Speaking drill",
          icon: "🗣️",
          skill: "speaking",
          xp: 30,
          exercises: [
            {
              type: "speak-phrase",
              prompt: "Say 'delicious'",
              display: "おいしい",
              romaji: "oishii",
              accept: ["oishi", "おいしい"],
              note: "A great word to know at any restaurant.",
            },
            {
              type: "speak-phrase",
              prompt: "Say 'This is big'",
              display: "おおきいです",
              romaji: "ookii desu",
              accept: ["ookii desu", "おおきいです", "okii desu"],
              note: "Drop the noun when it's obvious from context.",
            },
          ],
        },
      ],
    },
  ],
};
