import type { Level } from "@/lib/types";

// Beginner level — fully authored, kana + romaji (no raw kanji this stage).
// Five units spanning the four skills, getting harder as the learner advances.
export const beginner: Level = {
  id: "beginner",
  title: "Beginner",
  blurb: "Hiragana, greetings, numbers, nouns & adjectives.",
  units: [
    // ===== UNIT 1: Hiragana Foundations ====================================
    {
      id: "u1-hiragana",
      title: "Hiragana Foundations",
      subtitle: "Your first characters & sounds",
      lessons: [
        {
          id: "u1-vowels",
          title: "The 5 Vowels",
          subtitle: "あ い う え お",
          icon: "あ",
          skill: "writing",
          xp: 20,
          teach: [
            {
              char: "あ",
              romaji: "a",
              mnemonic: "あ hides a capital 'A' — see the cross and the curl. Say 'ah'.",
              mnemonicEmoji: "🅰️",
              example: { word: "あめ", romaji: "ame", meaning: "rain" },
            },
            {
              char: "い",
              romaji: "i",
              mnemonic: "い is two strokes side by side — like two little 'i's. Say 'ee'.",
              mnemonicEmoji: "🐟",
              example: { word: "いぬ", romaji: "inu", meaning: "dog" },
            },
            {
              char: "う",
              romaji: "u",
              mnemonic: "う is a person with a curl, leaning back going 'ooo'.",
              mnemonicEmoji: "🌊",
              example: { word: "うみ", romaji: "umi", meaning: "sea" },
            },
            {
              char: "え",
              romaji: "e",
              mnemonic: "え looks like an exotic bird or a ninja — 'eh?'",
              mnemonicEmoji: "🥷",
              example: { word: "えき", romaji: "eki", meaning: "station" },
            },
            {
              char: "お",
              romaji: "o",
              mnemonic: "お is a person kicking a ball — 'oh!'",
              mnemonicEmoji: "👹",
              example: { word: "おに", romaji: "oni", meaning: "ogre" },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "あ",
              options: ["a", "i", "u", "e"],
              answer: "a",
              note: "あ is pronounced like the 'a' in 'father'.",
            },
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "い",
              options: ["o", "e", "i", "a"],
              answer: "i",
              note: "い sounds like the 'ee' in 'see'.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this character",
              display: "う",
              answer: "u",
              note: "う sounds like the 'oo' in 'food'.",
            },
            {
              type: "match-pairs",
              prompt: "Match each character to its sound",
              pairs: [
                { left: "え", right: "e" },
                { left: "お", right: "o" },
                { left: "あ", right: "a" },
              ],
              note: "The five vowels are the foundation of every kana.",
            },
          ],
        },
        {
          id: "u1-ka-row",
          title: "The K-row",
          subtitle: "か き く け こ",
          icon: "か",
          skill: "writing",
          xp: 20,
          teach: [
            {
              char: "か",
              romaji: "ka",
              mnemonic: "か is literally the word for mosquito — picture it about to bite, 'ka!'",
              mnemonicEmoji: "🦟",
              example: { word: "かさ", romaji: "kasa", meaning: "umbrella" },
            },
            {
              char: "き",
              romaji: "ki",
              mnemonic: "き looks like a key. A key says 'kee'.",
              mnemonicEmoji: "🔑",
              example: { word: "き", romaji: "ki", meaning: "tree" },
            },
            {
              char: "く",
              romaji: "ku",
              mnemonic: "く is a bird's beak opening — a cuckoo going 'ku'.",
              mnemonicEmoji: "🐦",
              example: { word: "くつ", romaji: "kutsu", meaning: "shoes" },
            },
            {
              char: "け",
              romaji: "ke",
              mnemonic: "け looks like a kettle with the lid and handle. 'Keh'.",
              mnemonicEmoji: "🫖",
              example: { word: "けむり", romaji: "kemuri", meaning: "smoke" },
            },
            {
              char: "こ",
              romaji: "ko",
              mnemonic: "こ is two short strokes — like a small 'ko' (child).",
              mnemonicEmoji: "🍚",
              example: { word: "こめ", romaji: "kome", meaning: "(uncooked) rice" },
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "Which sound does this make?",
              display: "か",
              options: ["ka", "ki", "ku", "ko"],
              answer: "ka",
              note: "か = k + a.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for this character",
              display: "き",
              answer: "ki",
              note: "き = k + i.",
            },
            {
              type: "match-pairs",
              prompt: "Match each character to its sound",
              pairs: [
                { left: "く", right: "ku" },
                { left: "け", right: "ke" },
                { left: "こ", right: "ko" },
              ],
              note: "Notice the pattern: consonant + vowel.",
            },
          ],
        },
        {
          id: "u1-sa-row",
          title: "The S-row",
          subtitle: "さ し す せ そ",
          icon: "さ",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "さ", romaji: "sa", mnemonic: "さ looks like a fishhook — 'sa'.", example: { word: "あさ", romaji: "asa", meaning: "morning" } },
            { char: "し", romaji: "shi", mnemonic: "し is a single hook swooping down — 'shi'.", example: { word: "しか", romaji: "shika", meaning: "deer" } },
            { char: "す", romaji: "su", mnemonic: "す has a loop like a curl — 'su'.", example: { word: "すし", romaji: "sushi", meaning: "sushi" } },
            { char: "せ", romaji: "se", mnemonic: "せ looks like it says 'set' — 'se'.", example: { word: "せき", romaji: "seki", meaning: "seat" } },
            { char: "そ", romaji: "so", mnemonic: "そ zig-zags like needle & thread — 'so'.", example: { word: "うそ", romaji: "uso", meaning: "a lie" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "さ", options: ["sa", "shi", "su", "so"], answer: "sa" },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "し", options: ["se", "shi", "so", "sa"], answer: "shi", note: "し = 'shi', not 'si'." },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "す", answer: "su" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "そ", options: ["そ", "さ", "す", "せ"], answer: "そ" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "せ", right: "se" }, { left: "そ", right: "so" }, { left: "し", right: "shi" }] },
          ],
        },
        {
          id: "u1-ta-row",
          title: "The T-row",
          subtitle: "た ち つ て と",
          icon: "た",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "た", romaji: "ta", mnemonic: "た has a cross and a hook — 'ta'.", example: { word: "たこ", romaji: "tako", meaning: "octopus" } },
            { char: "ち", romaji: "chi", mnemonic: "ち is like a chin — 'chi'.", example: { word: "くち", romaji: "kuchi", meaning: "mouth" } },
            { char: "つ", romaji: "tsu", mnemonic: "つ is a swoosh like a wave — 'tsu'.", example: { word: "くつ", romaji: "kutsu", meaning: "shoes" } },
            { char: "て", romaji: "te", mnemonic: "て is one hook stroke — 'te'.", example: { word: "て", romaji: "te", meaning: "hand" } },
            { char: "と", romaji: "to", mnemonic: "と is a nail with a drop — 'to'.", example: { word: "いと", romaji: "ito", meaning: "thread" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "ち", options: ["chi", "ta", "tsu", "to"], answer: "chi", note: "ち = 'chi', not 'ti'." },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "つ", options: ["tsu", "te", "to", "ta"], answer: "tsu", note: "つ = 'tsu', not 'tu'." },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "た", answer: "ta" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "と", options: ["と", "て", "た", "ち"], answer: "と" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "て", right: "te" }, { left: "と", right: "to" }, { left: "た", right: "ta" }] },
          ],
        },
        {
          id: "u1-na-row",
          title: "The N-row",
          subtitle: "な に ぬ ね の",
          icon: "な",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "な", romaji: "na", mnemonic: "な has a cross and a knot — 'na'.", example: { word: "さかな", romaji: "sakana", meaning: "fish" } },
            { char: "に", romaji: "ni", mnemonic: "に looks like two marks — 'ni'.", example: { word: "にく", romaji: "niku", meaning: "meat" } },
            { char: "ぬ", romaji: "nu", mnemonic: "ぬ has a loop like noodles — 'nu'.", example: { word: "いぬ", romaji: "inu", meaning: "dog" } },
            { char: "ね", romaji: "ne", mnemonic: "ね has a loop with a tail — 'ne'.", example: { word: "ねこ", romaji: "neko", meaning: "cat" } },
            { char: "の", romaji: "no", mnemonic: "の is a single spiral — 'no'.", example: { word: "きのこ", romaji: "kinoko", meaning: "mushroom" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "ぬ", options: ["nu", "ne", "na", "no"], answer: "nu" },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "の", options: ["no", "na", "ni", "ne"], answer: "no" },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "に", answer: "ni" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "ね", options: ["ね", "な", "の", "ぬ"], answer: "ね" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "な", right: "na" }, { left: "に", right: "ni" }, { left: "の", right: "no" }] },
          ],
        },
        {
          id: "u1-ha-row",
          title: "The H-row",
          subtitle: "は ひ ふ へ ほ",
          icon: "は",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "は", romaji: "ha", mnemonic: "は looks like an 'H' shape — 'ha'.", example: { word: "はな", romaji: "hana", meaning: "flower / nose" } },
            { char: "ひ", romaji: "hi", mnemonic: "ひ is a wide smile — 'hi'.", example: { word: "ひと", romaji: "hito", meaning: "person" } },
            { char: "ふ", romaji: "fu", mnemonic: "ふ is scattered like Mt. Fuji — 'fu'.", example: { word: "ふね", romaji: "fune", meaning: "boat" } },
            { char: "へ", romaji: "he", mnemonic: "へ is a gentle hill — 'he'.", example: { word: "へそ", romaji: "heso", meaning: "navel" } },
            { char: "ほ", romaji: "ho", mnemonic: "ほ is は plus a stroke — 'ho'.", example: { word: "ほし", romaji: "hoshi", meaning: "star" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "ふ", options: ["fu", "ho", "hi", "ha"], answer: "fu", note: "ふ = 'fu', a soft h/f sound." },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "ほ", options: ["ho", "ha", "he", "hi"], answer: "ho" },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "ひ", answer: "hi" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "は", options: ["は", "へ", "ほ", "ふ"], answer: "は" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "へ", right: "he" }, { left: "ほ", right: "ho" }, { left: "ひ", right: "hi" }] },
          ],
        },
        {
          id: "u1-ma-row",
          title: "The M-row",
          subtitle: "ま み む め も",
          icon: "ま",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "ま", romaji: "ma", mnemonic: "ま has a loop at the bottom — 'ma'.", example: { word: "まめ", romaji: "mame", meaning: "bean" } },
            { char: "み", romaji: "mi", mnemonic: "み curls like the number 21 — 'mi'.", example: { word: "みみ", romaji: "mimi", meaning: "ear" } },
            { char: "む", romaji: "mu", mnemonic: "む has a loop and a flick — 'mu'.", example: { word: "むし", romaji: "mushi", meaning: "insect" } },
            { char: "め", romaji: "me", mnemonic: "め is a loop like an eye — 'me'.", example: { word: "め", romaji: "me", meaning: "eye" } },
            { char: "も", romaji: "mo", mnemonic: "も is a hook with two crosses — 'mo'.", example: { word: "もも", romaji: "momo", meaning: "peach" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "む", options: ["mu", "mo", "mi", "ma"], answer: "mu" },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "も", options: ["mo", "ma", "me", "mi"], answer: "mo" },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "み", answer: "mi" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "め", options: ["め", "ま", "も", "む"], answer: "め" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "ま", right: "ma" }, { left: "め", right: "me" }, { left: "も", right: "mo" }] },
          ],
        },
        {
          id: "u1-ya-row",
          title: "The Y-row",
          subtitle: "や ゆ よ",
          icon: "や",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "や", romaji: "ya", mnemonic: "や looks like a yak's horns — 'ya'.", example: { word: "やま", romaji: "yama", meaning: "mountain" } },
            { char: "ゆ", romaji: "yu", mnemonic: "ゆ has a loop like a fish — 'yu'.", example: { word: "ゆき", romaji: "yuki", meaning: "snow" } },
            { char: "よ", romaji: "yo", mnemonic: "よ is a hook with a loop — 'yo'.", example: { word: "よこ", romaji: "yoko", meaning: "side" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "や", options: ["ya", "yu", "yo", "wa"], answer: "ya" },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "ゆ", options: ["yu", "ya", "yo", "mu"], answer: "yu" },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "よ", answer: "yo" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "や", options: ["や", "よ", "ゆ", "な"], answer: "や" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "や", right: "ya" }, { left: "ゆ", right: "yu" }, { left: "よ", right: "yo" }] },
          ],
        },
        {
          id: "u1-ra-row",
          title: "The R-row",
          subtitle: "ら り る れ ろ",
          icon: "ら",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "ら", romaji: "ra", mnemonic: "ら is a flag on a pole — 'ra'.", example: { word: "そら", romaji: "sora", meaning: "sky" } },
            { char: "り", romaji: "ri", mnemonic: "り is two strokes — 'ri'.", example: { word: "とり", romaji: "tori", meaning: "bird" } },
            { char: "る", romaji: "ru", mnemonic: "る ends in a loop — 'ru'.", example: { word: "よる", romaji: "yoru", meaning: "night" } },
            { char: "れ", romaji: "re", mnemonic: "れ has a tail that curls out — 're'.", example: { word: "はれ", romaji: "hare", meaning: "sunny" } },
            { char: "ろ", romaji: "ro", mnemonic: "ろ is る without the loop — 'ro'.", example: { word: "いろ", romaji: "iro", meaning: "colour" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "る", options: ["ru", "ro", "ra", "ri"], answer: "ru", note: "る (loop) vs ろ (no loop)." },
            { type: "translate-choice", prompt: "Which sound does this make?", display: "ろ", options: ["ro", "ru", "re", "ra"], answer: "ro" },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "り", answer: "ri" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "れ", options: ["れ", "ら", "ろ", "る"], answer: "れ" },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "ら", right: "ra" }, { left: "れ", right: "re" }, { left: "ろ", right: "ro" }] },
          ],
        },
        {
          id: "u1-wa-row",
          title: "わ を ん",
          subtitle: "The last kana",
          icon: "ん",
          skill: "writing",
          xp: 20,
          teach: [
            { char: "わ", romaji: "wa", mnemonic: "わ has a tail — 'wa'.", example: { word: "かわ", romaji: "kawa", meaning: "river" } },
            { char: "を", romaji: "wo", mnemonic: "を is the object-marker particle — said 'o'.", example: { word: "を", romaji: "o", meaning: "marks the object of a verb" } },
            { char: "ん", romaji: "n", mnemonic: "ん is the only solo-consonant kana — 'n'.", example: { word: "ほん", romaji: "hon", meaning: "book" } },
          ],
          exercises: [
            { type: "translate-choice", prompt: "Which sound does this make?", display: "わ", options: ["wa", "wo", "n", "ra"], answer: "wa" },
            { type: "translate-choice", prompt: "Which kana is the 'n' sound?", display: "❓", options: ["ん", "わ", "を", "の"], answer: "ん" },
            { type: "type-answer", prompt: "Type the romaji for this character", display: "ん", answer: "n" },
            { type: "listen-choice", prompt: "Listen and tap the kana you hear", audio: "わ", options: ["わ", "を", "ん", "ら"], answer: "わ", note: "わ = 'wa'; を = 'o'; ん = 'n'." },
            { type: "match-pairs", prompt: "Match each character to its sound", pairs: [{ left: "わ", right: "wa" }, { left: "を", right: "wo (o)" }, { left: "ん", right: "n" }] },
          ],
        },
        {
          id: "u1-row-sort",
          title: "Sort the Rows",
          subtitle: "Vowels vs K-row",
          icon: "🗂️",
          skill: "writing",
          xp: 25,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each kana into its row",
              categories: ["Vowels (a/i/u…)", "K-row (ka/ki…)"],
              items: [
                { label: "あ", romaji: "a", category: "Vowels (a/i/u…)" },
                { label: "い", romaji: "i", category: "Vowels (a/i/u…)" },
                { label: "う", romaji: "u", category: "Vowels (a/i/u…)" },
                { label: "か", romaji: "ka", category: "K-row (ka/ki…)" },
                { label: "き", romaji: "ki", category: "K-row (ka/ki…)" },
                { label: "く", romaji: "ku", category: "K-row (ka/ki…)" },
              ],
              note: "Every K-row kana is just k + a vowel sound.",
            },
          ],
        },
        {
          id: "u1-listen",
          title: "Hear the Kana",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 25,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Listen and tap the kana you hear",
              audio: "あ",
              options: ["あ", "え", "お", "う"],
              answer: "あ",
              note: "Train your ear before your eyes — listen first.",
            },
            {
              type: "listen-choice",
              prompt: "Listen and tap the kana you hear",
              audio: "き",
              options: ["か", "き", "け", "く"],
              answer: "き",
              note: "き sounds like 'key'.",
            },
            {
              type: "listen-choice",
              prompt: "Listen and tap the kana you hear",
              audio: "こ",
              options: ["こ", "か", "く", "け"],
              answer: "こ",
              note: "こ sounds like 'co' in 'cocoa'.",
            },
          ],
        },
        {
          id: "u1-speak",
          title: "Say the Kana",
          subtitle: "Speaking drill",
          icon: "🗣️",
          skill: "speaking",
          xp: 25,
          exercises: [
            {
              type: "speak-phrase",
              prompt: "Say this sound aloud",
              display: "あ",
              romaji: "a",
              accept: ["a", "ah", "あー"],
              note: "Open your mouth wide — a clear 'ah'.",
            },
            {
              type: "speak-phrase",
              prompt: "Say this sound aloud",
              display: "か",
              romaji: "ka",
              accept: ["ka", "car"],
              note: "か — a crisp 'ka'.",
            },
            {
              type: "speak-phrase",
              prompt: "Say this sound aloud",
              display: "こ",
              romaji: "ko",
              accept: ["ko", "co"],
              note: "こ — like 'co' in 'cocoa'.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 2: Greetings & Self-Introduction ===========================
    {
      id: "u2-greetings",
      title: "Greetings & Self-Intro",
      subtitle: "Hello, thanks & your name",
      lessons: [
        {
          id: "u2-greetings-core",
          title: "Basic Greetings",
          subtitle: "Say hello & thanks",
          icon: "👋",
          skill: "writing",
          xp: 25,
          teach: [
            {
              kind: "phrase",
              term: "おはよう",
              reading: "ohayou",
              meaning: "Good morning",
              parts: [
                { kana: "お", reading: "o" },
                { kana: "は", reading: "ha", note: "A normal 'ha' here — not the 'wa' particle." },
                { kana: "よ", reading: "yo" },
                { kana: "う", reading: "u", note: "Lengthens the 'yo' → 'ohayoo'." },
              ],
              check: {
                prompt: "Tap the part you already learned in Unit 1",
                options: ["お", "は", "よ"],
                answer: "お",
                note: "お and う are both vowels from Unit 1.",
              },
              context: "Morning greeting — to friends, family or colleagues.",
              polite: { term: "おはようございます", reading: "ohayou gozaimasu" },
              trace: "お",
            },
            {
              kind: "phrase",
              term: "こんにちは",
              reading: "konnichiwa",
              meaning: "Hello (daytime)",
              parts: [
                { kana: "こ", reading: "ko" },
                { kana: "ん", reading: "n" },
                { kana: "に", reading: "ni" },
                { kana: "ち", reading: "chi" },
                { kana: "は", reading: "wa", base: "ha", note: "This は is the topic particle, so it's said 'wa'." },
              ],
              check: {
                prompt: "Which part is said 'wa' (not 'ha')?",
                options: ["こ", "に", "は"],
                answer: "は",
                note: "The は at the end is the topic particle — always 'wa'.",
              },
              context: "Daytime 'hello', from late morning into the evening.",
              trace: "こ",
            },
            {
              kind: "phrase",
              term: "こんばんは",
              reading: "konbanwa",
              meaning: "Good evening",
              parts: [
                { kana: "こ", reading: "ko" },
                { kana: "ん", reading: "n" },
                { kana: "ば", reading: "ba" },
                { kana: "ん", reading: "n" },
                { kana: "は", reading: "wa", base: "ha", note: "Same rule as こんにちは — sentence-final は is 'wa'." },
              ],
              check: {
                prompt: "Like こんにちは, how is the final は said?",
                options: ["ha", "wa"],
                answer: "wa",
                note: "Sentence-ending topic-particle は = 'wa'.",
              },
              context: "Evening greeting.",
              trace: "こ",
            },
            {
              kind: "phrase",
              term: "ありがとう",
              reading: "arigatou",
              meaning: "Thank you",
              parts: [
                { kana: "あ", reading: "a" },
                { kana: "り", reading: "ri" },
                { kana: "が", reading: "ga" },
                { kana: "と", reading: "to" },
                { kana: "う", reading: "u" },
              ],
              check: {
                prompt: "Which part is a vowel from Unit 1?",
                options: ["り", "が", "あ"],
                answer: "あ",
              },
              context: "Casual 'thank you'.",
              polite: { term: "ありがとうございます", reading: "arigatou gozaimasu" },
              trace: "あ",
            },
          ],
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the greeting to its meaning",
              pairs: [
                { left: "おはよう", right: "Good morning" },
                { left: "こんにちは", right: "Hello (daytime)" },
                { left: "こんばんは", right: "Good evening" },
                { left: "ありがとう", right: "Thank you" },
              ],
              note: "は in greetings is pronounced 'wa'.",
            },
            {
              type: "translate-choice",
              prompt: "What do you say in the evening?",
              display: "🌙",
              options: ["おはよう", "こんにちは", "こんばんは", "ありがとう"],
              answer: "こんばんは",
              note: "こんばんは (konbanwa) — good evening.",
            },
            {
              type: "type-answer",
              prompt: "How do you say 'Good morning'? (romaji)",
              display: "おはよう",
              answer: "ohayou",
              accept: ["ohayo"],
              note: "おはよう (ohayou) — add ございます to be polite.",
            },
          ],
        },
        {
          id: "u2-self-intro",
          title: "Introducing Yourself",
          subtitle: "Name & nice to meet you",
          icon: "🙋",
          skill: "writing",
          xp: 30,
          teach: [
            {
              kind: "phrase",
              term: "はじめまして",
              reading: "hajimemashite",
              meaning: "Nice to meet you",
              parts: [
                { kana: "は", reading: "ha", note: "Here は is a normal 'ha' — not the 'wa' particle." },
                { kana: "じ", reading: "ji" },
                { kana: "め", reading: "me" },
                { kana: "ま", reading: "ma" },
                { kana: "し", reading: "shi" },
                { kana: "て", reading: "te" },
              ],
              check: {
                prompt: "In はじめまして, は is said…",
                options: ["ha", "wa"],
                answer: "ha",
                note: "Only sentence-final topic-particle は becomes 'wa'. Here it's a normal 'ha'.",
              },
              context: "Said when meeting someone new — usually paired with よろしく.",
            },
            {
              kind: "phrase",
              term: "です",
              reading: "desu",
              meaning: "am / is (polite)",
              parts: [
                { kana: "で", reading: "de" },
                { kana: "す", reading: "su", note: "The 'u' is often barely voiced → 'des'." },
              ],
              context: "Attach to a noun: わたしは たなか です = 'I am Tanaka'.",
            },
            {
              kind: "phrase",
              term: "よろしく",
              reading: "yoroshiku",
              meaning: "Please be kind to me",
              parts: [
                { kana: "よ", reading: "yo" },
                { kana: "ろ", reading: "ro" },
                { kana: "し", reading: "shi" },
                { kana: "く", reading: "ku" },
              ],
              context: "Often follows your name when introducing yourself.",
              polite: { term: "よろしくおねがいします", reading: "yoroshiku onegaishimasu" },
              trace: "く",
            },
            {
              kind: "phrase",
              term: "すみません",
              reading: "sumimasen",
              meaning: "Excuse me / Sorry",
              parts: [
                { kana: "す", reading: "su" },
                { kana: "み", reading: "mi" },
                { kana: "ま", reading: "ma" },
                { kana: "せ", reading: "se" },
                { kana: "ん", reading: "n" },
              ],
              context: "Works for both 'excuse me' (getting attention) and 'sorry'.",
            },
          ],
          exercises: [
            {
              type: "translate-choice",
              prompt: "Select the meaning",
              display: "はじめまして",
              options: [
                "Nice to meet you",
                "See you later",
                "I'm sorry",
                "Excuse me",
              ],
              answer: "Nice to meet you",
              note: "はじめまして (hajimemashite) opens a first meeting.",
            },
            {
              type: "build-sentence",
              prompt: "Build: 'I am Tanaka' (watashi wa Tanaka desu)",
              display: "I am Tanaka",
              tiles: ["わたし", "は", "たなか", "です"],
              answer: ["わたし", "は", "たなか", "です"],
              note: "わたしは X です = 'I am X'. Polite and simple.",
            },
            {
              type: "match-pairs",
              prompt: "Match the phrase to its meaning",
              pairs: [
                { left: "よろしく", right: "Please be kind to me" },
                { left: "すみません", right: "Excuse me / Sorry" },
              ],
              note: "よろしく often follows your introduction.",
            },
          ],
        },
        {
          id: "u2-listen",
          title: "Which Greeting?",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 30,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Which greeting did you hear?",
              audio: "こんにちは",
              options: ["Hello", "Good evening", "Thank you", "Goodbye"],
              answer: "Hello",
              note: "こんにちは — the daytime hello.",
            },
            {
              type: "listen-choice",
              prompt: "What did you hear?",
              audio: "はじめまして",
              options: ["Nice to meet you", "Goodbye", "Thank you", "Excuse me"],
              answer: "Nice to meet you",
              note: "はじめまして opens a first meeting.",
            },
          ],
        },
        {
          id: "u2-speak",
          title: "Greet Out Loud",
          subtitle: "Speaking drill",
          icon: "🗣️",
          skill: "speaking",
          xp: 30,
          exercises: [
            {
              type: "speak-phrase",
              prompt: "Say 'Hello'",
              display: "こんにちは",
              romaji: "konnichiwa",
              accept: ["こんにちわ", "konnichiwa", "konnichwa"],
              note: "Written こんにちは, said 'konnichiwa'.",
            },
            {
              type: "speak-phrase",
              prompt: "Say 'Thank you'",
              display: "ありがとう",
              romaji: "arigatou",
              accept: ["ありがとうございます", "arigato", "arigatou"],
              note: "Add ございます to sound more polite.",
            },
          ],
        },
        {
          id: "u2-punctuation",
          title: "Punctuation Dojo",
          subtitle: "。 、 「」 ー っ",
          icon: "。",
          skill: "punctuation",
          xp: 30,
          exercises: [
            {
              type: "translate-choice",
              prompt: "What is 。 used for?",
              display: "。",
              options: [
                "End of a sentence (full stop)",
                "A comma / pause",
                "A question",
                "A long vowel",
              ],
              answer: "End of a sentence (full stop)",
              note: "。 (maru) is the Japanese full stop.",
            },
            {
              type: "translate-choice",
              prompt: "The small っ doubles a consonant. How is がっこう read?",
              display: "がっこう",
              options: ["gakkou (double k)", "gako", "gatsukou", "ga-ko-u"],
              answer: "gakkou (double k)",
              note: "Small っ (sokuon) doubles the next consonant: gak-kou.",
            },
            {
              type: "build-sentence",
              prompt: "Build 'Hello.' with the right full stop",
              display: "Hello.",
              tiles: ["こんにちは", "。"],
              answer: ["こんにちは", "。"],
              note: "Statements end with 。 — don't forget it.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 3: Numbers, Age & Time =====================================
    {
      id: "u3-numbers",
      title: "Numbers, Age & Time",
      subtitle: "Count, say your age & ask the time",
      lessons: [
        {
          id: "u3-numbers-1-10",
          title: "Numbers 1–10",
          subtitle: "いち に さん …",
          icon: "🔢",
          skill: "writing",
          xp: 25,
          teach: [
            { kind: "phrase", term: "いち", reading: "ichi", meaning: "one (1)" },
            { kind: "phrase", term: "に", reading: "ni", meaning: "two (2)" },
            { kind: "phrase", term: "さん", reading: "san", meaning: "three (3)" },
            { kind: "phrase", term: "よん", reading: "yon", meaning: "four (4)", note: "Also read し (shi)." },
            { kind: "phrase", term: "ご", reading: "go", meaning: "five (5)" },
            { kind: "phrase", term: "じゅう", reading: "juu", meaning: "ten (10)", note: "6–10: ろく なな はち きゅう じゅう." },
          ],
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the number to its digit",
              pairs: [
                { left: "いち", right: "1" },
                { left: "に", right: "2" },
                { left: "さん", right: "3" },
                { left: "ご", right: "5" },
              ],
              note: "1=いち, 2=に, 3=さん, 4=よん, 5=ご.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for 7 (なな)",
              display: "なな",
              answer: "nana",
              accept: ["shichi", "しち", "nana"],
              note: "7 is なな (nana) or しち (shichi).",
            },
          ],
        },
        {
          id: "u3-number-sort",
          title: "Sort the Numbers",
          subtitle: "1–5 vs 6–10",
          icon: "🗂️",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each number into the right range",
              categories: ["1–5", "6–10"],
              items: [
                { label: "いち", romaji: "1", category: "1–5" },
                { label: "さん", romaji: "3", category: "1–5" },
                { label: "ご", romaji: "5", category: "1–5" },
                { label: "なな", romaji: "7", category: "6–10" },
                { label: "はち", romaji: "8", category: "6–10" },
                { label: "じゅう", romaji: "10", category: "6–10" },
              ],
              note: "6=ろく, 7=なな, 8=はち, 9=きゅう, 10=じゅう.",
            },
          ],
        },
        {
          id: "u3-age-time",
          title: "Age & Asking the Time",
          subtitle: "〜さい です",
          icon: "⏰",
          skill: "writing",
          xp: 30,
          teach: [
            { kind: "phrase", term: "〜さい", reading: "sai", meaning: "~ years old", note: "わたしは ごさい です = 'I am 5 years old'." },
            { kind: "phrase", term: "なんさいですか", reading: "nansai desu ka", meaning: "How old are you?" },
            { kind: "phrase", term: "いまなんじですか", reading: "ima nanji desu ka", meaning: "What time is it now?" },
          ],
          exercises: [
            {
              type: "build-sentence",
              prompt: "Build: 'I am 5 years old' (watashi wa go-sai desu)",
              display: "I am 5 years old",
              tiles: ["わたし", "は", "ご", "さい", "です"],
              answer: ["わたし", "は", "ご", "さい", "です"],
              note: "〜さい (sai) = the 'years old' counter.",
            },
            {
              type: "match-pairs",
              prompt: "Match the question to its meaning",
              pairs: [
                { left: "なんさいですか", right: "How old are you?" },
                { left: "いまなんじですか", right: "What time is it?" },
              ],
              note: "なん (nan) = 'what / how many'.",
            },
          ],
        },
        {
          id: "u3-listen",
          title: "Hear the Number",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 30,
          exercises: [
            {
              type: "listen-choice",
              prompt: "Which number did you hear?",
              audio: "さん",
              options: ["1", "3", "5", "8"],
              answer: "3",
              note: "さん (san) = 3.",
            },
            {
              type: "listen-choice",
              prompt: "Which number did you hear?",
              audio: "じゅう",
              options: ["6", "7", "9", "10"],
              answer: "10",
              note: "じゅう (juu) = 10.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 4: Essential Nouns & Categorising ==========================
    {
      id: "u4-nouns",
      title: "Nouns & Categorising",
      subtitle: "People, things & food",
      lessons: [
        {
          id: "u4-family",
          title: "Family & People",
          subtitle: "おかあさん おとうさん …",
          icon: "👪",
          skill: "writing",
          xp: 25,
          teach: [
            { kind: "phrase", term: "おかあさん", reading: "okaasan", meaning: "mother" },
            { kind: "phrase", term: "おとうさん", reading: "otousan", meaning: "father" },
            { kind: "phrase", term: "あに", reading: "ani", meaning: "older brother" },
            { kind: "phrase", term: "いもうと", reading: "imouto", meaning: "younger sister" },
          ],
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the word to its meaning",
              pairs: [
                { left: "おかあさん", right: "mother" },
                { left: "おとうさん", right: "father" },
                { left: "あに", right: "older brother" },
                { left: "いもうと", right: "younger sister" },
              ],
              note: "Family words often start with お as politeness.",
            },
          ],
        },
        {
          id: "u4-people-things",
          title: "People vs Things",
          subtitle: "Sorting game",
          icon: "🗂️",
          skill: "writing",
          xp: 30,
          teach: [
            { kind: "phrase", term: "せんせい", reading: "sensei", meaning: "teacher" },
            { kind: "phrase", term: "ほん", reading: "hon", meaning: "book" },
            { kind: "phrase", term: "くるま", reading: "kuruma", meaning: "car" },
            { kind: "phrase", term: "でんわ", reading: "denwa", meaning: "phone" },
          ],
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each word: a person or a thing?",
              categories: ["ひと (people)", "もの (things)"],
              items: [
                { label: "おかあさん", romaji: "okaasan", category: "ひと (people)" },
                { label: "おとうさん", romaji: "otousan", category: "ひと (people)" },
                { label: "せんせい", romaji: "sensei", category: "ひと (people)" },
                { label: "ほん", romaji: "hon (book)", category: "もの (things)" },
                { label: "くるま", romaji: "kuruma (car)", category: "もの (things)" },
                { label: "でんわ", romaji: "denwa (phone)", category: "もの (things)" },
              ],
              note: "せんせい (sensei) = teacher.",
            },
          ],
        },
        {
          id: "u4-food-objects",
          title: "Food vs Objects",
          subtitle: "Sorting game",
          icon: "🍙",
          skill: "writing",
          xp: 30,
          teach: [
            { kind: "phrase", term: "ごはん", reading: "gohan", meaning: "rice / meal" },
            { kind: "phrase", term: "さかな", reading: "sakana", meaning: "fish" },
            { kind: "phrase", term: "りんご", reading: "ringo", meaning: "apple" },
            { kind: "phrase", term: "やさい", reading: "yasai", meaning: "vegetable" },
            { kind: "phrase", term: "いえ", reading: "ie", meaning: "house" },
            { kind: "phrase", term: "つくえ", reading: "tsukue", meaning: "desk" },
          ],
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each word: food or object?",
              categories: ["たべもの (food)", "もの (objects)"],
              items: [
                { label: "ごはん", romaji: "gohan (rice)", category: "たべもの (food)" },
                { label: "さかな", romaji: "sakana (fish)", category: "たべもの (food)" },
                { label: "りんご", romaji: "ringo (apple)", category: "たべもの (food)" },
                { label: "やさい", romaji: "yasai (veg)", category: "たべもの (food)" },
                { label: "いえ", romaji: "ie (house)", category: "もの (objects)" },
                { label: "でんわ", romaji: "denwa (phone)", category: "もの (objects)" },
              ],
              note: "ごはん means both 'rice' and 'a meal'.",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for 'apple' (りんご)",
              display: "りんご",
              answer: "ringo",
              note: "りんご (ringo) = apple.",
            },
          ],
        },
        {
          id: "u4-listen",
          title: "Hear the Noun",
          subtitle: "Listening drill",
          icon: "👂",
          skill: "listening",
          xp: 30,
          exercises: [
            {
              type: "listen-choice",
              prompt: "What did you hear?",
              audio: "ごはん",
              options: ["rice / meal", "car", "phone", "fish"],
              answer: "rice / meal",
              note: "ごはん (gohan).",
            },
            {
              type: "listen-choice",
              prompt: "What did you hear?",
              audio: "くるま",
              options: ["house", "car", "book", "apple"],
              answer: "car",
              note: "くるま (kuruma) = car.",
            },
          ],
        },
      ],
    },

    // ===== UNIT 5: Adjectives & Descriptions ===============================
    {
      id: "u5-adjectives",
      title: "Adjectives & Descriptions",
      subtitle: "Describe things around you",
      lessons: [
        {
          id: "u5-size-temp",
          title: "Big/Small, Hot/Cold",
          subtitle: "おおきい ちいさい …",
          icon: "📏",
          skill: "writing",
          xp: 25,
          teach: [
            { kind: "phrase", term: "おおきい", reading: "ookii", meaning: "big" },
            { kind: "phrase", term: "ちいさい", reading: "chiisai", meaning: "small" },
            { kind: "phrase", term: "あつい", reading: "atsui", meaning: "hot" },
            { kind: "phrase", term: "さむい", reading: "samui", meaning: "cold", note: "Most basic adjectives end in い." },
          ],
          exercises: [
            {
              type: "match-pairs",
              prompt: "Match the adjective to its meaning",
              pairs: [
                { left: "おおきい", right: "big" },
                { left: "ちいさい", right: "small" },
                { left: "あつい", right: "hot" },
                { left: "さむい", right: "cold" },
              ],
              note: "Most basic adjectives end in い.",
            },
            {
              type: "build-sentence",
              prompt: "Build: 'This book is big' (kono hon wa ookii desu)",
              display: "This book is big",
              tiles: ["この", "ほん", "は", "おおきい", "です"],
              answer: ["この", "ほん", "は", "おおきい", "です"],
              note: "この X は ... です = 'This X is ...'.",
            },
          ],
        },
        {
          id: "u5-sort",
          title: "Size vs Temperature",
          subtitle: "Sorting game",
          icon: "🗂️",
          skill: "writing",
          xp: 30,
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each adjective by what it describes",
              categories: ["size", "temperature"],
              items: [
                { label: "おおきい", romaji: "ookii (big)", category: "size" },
                { label: "ちいさい", romaji: "chiisai (small)", category: "size" },
                { label: "あつい", romaji: "atsui (hot)", category: "temperature" },
                { label: "さむい", romaji: "samui (cold)", category: "temperature" },
              ],
              note: "あつい can mean hot weather or a hot object.",
            },
          ],
        },
        {
          id: "u5-positive-negative",
          title: "Good vs Bad",
          subtitle: "Sorting game",
          icon: "⚖️",
          skill: "writing",
          xp: 30,
          teach: [
            { kind: "phrase", term: "おいしい", reading: "oishii", meaning: "delicious" },
            { kind: "phrase", term: "まずい", reading: "mazui", meaning: "bad-tasting" },
            { kind: "phrase", term: "いい", reading: "ii", meaning: "good" },
            { kind: "phrase", term: "わるい", reading: "warui", meaning: "bad" },
            { kind: "phrase", term: "あたらしい", reading: "atarashii", meaning: "new" },
            { kind: "phrase", term: "ふるい", reading: "furui", meaning: "old" },
          ],
          exercises: [
            {
              type: "category-sort",
              prompt: "Park each word: positive or negative?",
              categories: ["positive", "negative"],
              items: [
                { label: "おいしい", romaji: "oishii (tasty)", category: "positive" },
                { label: "いい", romaji: "ii (good)", category: "positive" },
                { label: "あたらしい", romaji: "atarashii (new)", category: "positive" },
                { label: "まずい", romaji: "mazui (bad taste)", category: "negative" },
                { label: "わるい", romaji: "warui (bad)", category: "negative" },
                { label: "ふるい", romaji: "furui (old)", category: "negative" },
              ],
              note: "Context matters — 'old' isn't always negative!",
            },
            {
              type: "type-answer",
              prompt: "Type the romaji for 'delicious' (おいしい)",
              display: "おいしい",
              answer: "oishii",
              accept: ["oishi"],
              note: "おいしい (oishii) = delicious.",
            },
          ],
        },
        {
          id: "u5-speak",
          title: "Describe It Out Loud",
          subtitle: "Speaking drill",
          icon: "🗣️",
          skill: "speaking",
          xp: 30,
          exercises: [
            {
              type: "speak-phrase",
              prompt: "Say 'delicious'",
              display: "おいしい",
              romaji: "oishii",
              accept: ["oishi", "おいしい"],
              note: "A great word to know at any restaurant.",
            },
            {
              type: "speak-phrase",
              prompt: "Say 'This is big'",
              display: "おおきいです",
              romaji: "ookii desu",
              accept: ["ookii desu", "おおきいです", "okii desu"],
              note: "Drop the noun when it's obvious from context.",
            },
          ],
        },
      ],
    },
  ],
};
